package com.hisho.tether;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.webkit.*;import android.webkit.JavascriptInterface;import android.widget.*;import org.json.*;import java.util.*;
public class FottoLoginActivity extends Activity{
 static final String LOGIN="https://auth.alboompro.com/login?srv=fotto&redir=/&host=https://fotto.alboompro.com";WebView web;TextView status;boolean delivered=false;String pendingApiKey="";
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xfff7f9fc);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(8),dp(16),dp(8));bar.setBackgroundColor(Color.WHITE);status=new TextView(this);status.setText("LUMO · conectar ao Fotto");status.setTextColor(0xff0b1220);status.setTextSize(14);bar.addView(status,new LinearLayout.LayoutParams(0,dp(48),1));Button cancel=new Button(this);cancel.setText("Fechar");cancel.setAllCaps(false);cancel.setOnClickListener(v->{setResult(RESULT_CANCELED);finish();});bar.addView(cancel,new LinearLayout.LayoutParams(dp(90),dp(48)));root.addView(bar);web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);setup();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 void setup(){WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setUserAgentString(s.getUserAgentString()+" LUMO/0.9.3");CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.addJavascriptInterface(new Bridge(),"FottoBridge");web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){captureUrl(r.getUrl().toString());return false;}public void onPageFinished(WebView v,String u){status.setText(u.contains("fotto.alboompro.com")?"Capturando sessão Fotto…":"Faça login para continuar");captureUrl(u);captureStorage();}});web.loadUrl(LOGIN);}
 class Bridge{@JavascriptInterface public void onSessionReady(String apiKey){runOnUiThread(()->{if(valid(apiKey)){pendingApiKey=FottoApi.stripBearer(apiKey);captureStorage();}});}}
 void captureUrl(String raw){try{Uri u=Uri.parse(raw);String host=u.getHost();if(host==null||!host.toLowerCase(Locale.ROOT).contains("fotto.alboompro.com"))return;for(String k:new String[]{"access_token","accessToken"}){String v=u.getQueryParameter(k);if(valid(v)){deliver(v,pendingApiKey);return;}}for(String k:new String[]{"apiKey","api_key","apikey"}){String v=u.getQueryParameter(k);if(valid(v))pendingApiKey=FottoApi.stripBearer(v);}}catch(Exception ignored){}}
 void captureStorage(){String js="(function(){try{var out={access:'',apiKey:''};function scan(s){if(!s)return;for(var i=0;i<s.length;i++){var k=s.key(i)||'',v=s.getItem(k)||'',low=k.toLowerCase();if(!out.access&&(low==='access_token'||low==='accesstoken'))out.access=v;if(!out.apiKey&&(low==='apikey'||low==='api_key'))out.apiKey=v;try{var o=JSON.parse(v);if(o&&typeof o==='object'){if(!out.access)out.access=o.access_token||o.accessToken||'';if(!out.apiKey)out.apiKey=o.apiKey||o.api_key||'';}}catch(e){}}}scan(window.localStorage);scan(window.sessionStorage);return JSON.stringify(out);}catch(e){return '{}';}})();";web.evaluateJavascript(js,val->{try{Object outer=new JSONTokener(val).nextValue();String raw=outer instanceof String?(String)outer:String.valueOf(outer);JSONObject o=new JSONObject(raw);String access=clean(o.optString("access","")),key=clean(o.optString("apiKey",pendingApiKey));if(valid(key))pendingApiKey=key;if(valid(access)){deliver(access,key);return;}if(valid(key)&&web!=null){String url=web.getUrl();if(url!=null&&url.contains("fotto.alboompro.com"))deliver(key,key);}}catch(Exception ignored){}});}
 String clean(String s){if(s==null)return "";s=s.trim();if(s.regionMatches(true,0,"Bearer ",0,7))s=s.substring(7).trim();if(s.startsWith("\"")&&s.endsWith("\"")&&s.length()>2)s=s.substring(1,s.length()-1);return s;}
 boolean valid(String s){if(s==null)return false;s=clean(s);return s.length()>20&&(s.indexOf('.')>0||s.length()>40);}
 void deliver(String access,String apiKey){if(delivered)return;access=clean(access);apiKey=clean(apiKey);if(!valid(access)&&valid(apiKey))access=apiKey;if(!valid(access))return;delivered=true;getSharedPreferences("hisho",0).edit().putString("fottoAccessTokenV4",access).putString("fottoApiKeyV4",valid(apiKey)?apiKey:"").remove("fottoToken").remove("fottoTokenV2").remove("fottoTokenV3").putString("fottoLastStatus","Fotto conectado ao LUMO.").apply();Intent data=new Intent().putExtra("fottoToken",access);setResult(RESULT_OK,data);finish();}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
 protected void onDestroy(){if(web!=null){web.stopLoading();web.destroy();web=null;}super.onDestroy();}
}
