package com.hisho.tether;
import android.content.*;import android.net.Uri;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;
final class FottoSync{
 private static final ExecutorService EXEC=Executors.newSingleThreadExecutor();private static final AtomicBoolean RUNNING=new AtomicBoolean(false);
 static void kick(Context c){long after=c.getSharedPreferences("hisho",0).getLong("fottoStartRowid",Long.MAX_VALUE);kick(c,after,false);}
 static void sendExisting(Context c){kick(c,0,true);}
 static void kick(Context source,long after,boolean resetErrors){Context c=source.getApplicationContext();android.content.SharedPreferences p=c.getSharedPreferences("hisho",0);if(!p.getBoolean("fottoAuto",false)&&!resetErrors)return;if(FottoApi.token(c).isEmpty()||p.getString("fottoGalleryId","").isEmpty())return;if(!RUNNING.compareAndSet(false,true))return;EXEC.execute(()->run(c,after,resetErrors));}
 static void sendSelected(Context source,Collection<String> ids){if(ids==null||ids.isEmpty())return;Context c=source.getApplicationContext();android.content.SharedPreferences p=c.getSharedPreferences("hisho",0);if(FottoApi.token(c).isEmpty()||p.getString("fottoGalleryId","").isEmpty()){p.edit().putString("fottoLastStatus","Conecte o Fotto e escolha um evento antes de enviar.").apply();return;}if(!RUNNING.compareAndSet(false,true))return;ArrayList<String> copy=new ArrayList<>(ids);EXEC.execute(()->runSelected(c,copy));}
 private static void run(Context c,long after,boolean resetErrors){Jobs jobs=new Jobs(c);android.content.SharedPreferences p=c.getSharedPreferences("hisho",0);String gallery=p.getString("fottoGalleryId",""),title=p.getString("fottoGalleryTitle","Evento");try{jobs.fottoRecover(gallery);if(resetErrors)jobs.fottoRetry(gallery);int sent=0;while(sent<40){String[] x=jobs.nextFotto(gallery,after);if(x==null)break;String id=x[0],name=x[1],uri=x[2];try{jobs.fottoSet(id,gallery,"uploading","","",true);p.edit().putString("fottoLastStatus","Enviando "+name+" → "+title).apply();FottoApi.Uploaded done=FottoApi.upload(c,Uri.parse(uri),name,gallery);jobs.fottoSet(id,gallery,"done",done.mediaId,"",false);int total=p.getInt("fottoUploadedCount",0)+1;p.edit().putInt("fottoUploadedCount",total).putString("fottoLastStatus","Enviado · "+name).putLong("fottoLastUploadAt",System.currentTimeMillis()).apply();sent++;}catch(Exception e){jobs.fottoSet(id,gallery,"error","",e.getMessage()==null?e.toString():e.getMessage(),false);p.edit().putString("fottoLastStatus","Falha no Fotto · "+(e.getMessage()==null?e.toString():e.getMessage())).apply();break;}}
   if(sent==0&&resetErrors)p.edit().putString("fottoLastStatus","Nenhuma Editada pendente para este evento.").apply();
  }catch(Exception e){p.edit().putString("fottoLastStatus","Falha na fila Fotto · "+e.getMessage()).apply();}finally{jobs.close();RUNNING.set(false);}}
 private static void runSelected(Context c,ArrayList<String> ids){Jobs jobs=new Jobs(c);android.content.SharedPreferences p=c.getSharedPreferences("hisho",0);String gallery=p.getString("fottoGalleryId",""),title=p.getString("fottoGalleryTitle","Evento");int sent=0,skipped=0;try{for(String id:ids){String[] j=jobs.editorJob(id);if(j==null||!"done".equals(j[5])||j[4]==null||j[4].isEmpty()){skipped++;continue;}if(jobs.fottoWasSent(id,gallery)){skipped++;continue;}String name=j[1].replaceFirst("(?i)\\.jpg$","_Editada.jpg");try{jobs.fottoSet(id,gallery,"uploading","","",true);p.edit().putString("fottoLastStatus","Enviando "+name+" → "+title).apply();FottoApi.Uploaded done=FottoApi.upload(c,Uri.parse(j[4]),name,gallery);jobs.fottoSet(id,gallery,"done",done.mediaId,"",false);sent++;p.edit().putInt("fottoUploadedCount",p.getInt("fottoUploadedCount",0)+1).putString("fottoLastStatus","Enviado · "+name).putLong("fottoLastUploadAt",System.currentTimeMillis()).apply();}catch(Exception e){jobs.fottoSet(id,gallery,"error","",e.getMessage()==null?e.toString():e.getMessage(),false);p.edit().putString("fottoLastStatus","Falha no Fotto · "+(e.getMessage()==null?e.toString():e.getMessage())).apply();break;}}
   if(sent>0)p.edit().putString("fottoLastStatus",sent+" foto(s) selecionada(s) enviadas"+(skipped>0?" · "+skipped+" ignorada(s)":"")).apply();else if(skipped>0)p.edit().putString("fottoLastStatus","As fotos selecionadas já foram enviadas ou ainda não estão aprovadas.").apply();
  }finally{jobs.close();RUNNING.set(false);}}
 static boolean running(){return RUNNING.get();}
}
