package com.hisho.tether;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.hardware.usb.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import android.net.Uri;import android.database.Cursor;import android.provider.OpenableColumns;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
 static final String USB="com.hisho.tether.USB_PERMISSION";
 final int BG=0xfff7f9fc,CARD=0xffffffff,LINE=0xffe5eaf0,TEXT=0xff0b1220,MUTED=0xff6f7d91,BLUE=0xff0b7cff,CYAN=0xff22dff3,SUCCESS=0xff20b46a,WARNING=0xffff9f43,ERROR=0xffe05454,DARK=0xff101820;
 private TextView status,report,presetLabel,originalCount,editedCount,pendingCount,badge,timing,previewTitle,previewSub,lockNote,folderLabel,globalFlowBar,previewState,previewScore;
 private TextView centerCamera,centerCapture,centerCurator,centerFotto,galleryTaskLabel,editSelectionLabel;
 private TextView fottoStatus,fottoUploadStatus,fottoSourceLabel,deliveryDone,deliveryUploading,deliveryPending,deliveryFailed,deliveryHeader;
 private Spinner fottoEvents;private CompoundButton fottoAuto;private Button fottoConnect,fottoRefresh,fottoSend;private boolean settingFottoEvents;private final ArrayList<FottoApi.Gallery> fottoGalleries=new ArrayList<>();private final ExecutorService fottoNetwork=Executors.newSingleThreadExecutor();
 private CompoundButton auto,preset,curation,backfill;private Spinner resolution,curationSensitivity;private final Handler handler=new Handler();private JSONObject presetData;private String presetName="Vibrant";private Button connect,load,resume,folderButton;private boolean registered;
 private LinearLayout[] pages=new LinearLayout[4];private ScrollView[] scrollers=new ScrollView[4];private Button[] tabs=new Button[4];private int selected=0;
 private FrameLayout previewFrame;private LinearLayout empty;private ImageView preview;private Bitmap previewBitmap;private String shownUri="",requestedUri="";private volatile long previewGeneration=0;private volatile boolean destroyed;
 private HorizontalScrollView filmScroll;private LinearLayout filmStrip;private Button previousPhoto,nextPhoto,livePhoto;private TextView galleryInfo;
 private final GallerySelection gallery=new GallerySelection();private String gallerySignature="";private final Map<String,FrameLayout> tiles=new HashMap<>();private final Map<String,String> photoStates=new HashMap<>();private final Map<String,Integer> photoScores=new HashMap<>();
 private final ExecutorService thumbnails=Executors.newSingleThreadExecutor();private final android.util.LruCache<String,Bitmap> thumbCache=new android.util.LruCache<String,Bitmap>(8*1024*1024){protected int sizeOf(String key,Bitmap b){return b.getByteCount();}};private volatile long stripGeneration=0;
 private final ExecutorService images=Executors.newSingleThreadExecutor();private Jobs database;private final LinkedHashSet<String> editSelection=new LinkedHashSet<>();
 private LinearLayout galleryQueue,deliveryQueue,captureSettingsPanel,deliverySettingsPanel,backfillBanner;private TextView backfillBannerText;private Button backfillDownload,backfillIgnore;private String galleryFilter="all";private Button[] galleryFilterButtons=new Button[5];private String galleryListSignature="",deliverySignature="";

 private final BroadcastReceiver receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(USB.equals(i.getAction())){UsbDevice d=i.getParcelableExtra(UsbManager.EXTRA_DEVICE);if(d!=null&&((UsbManager)getSystemService(USB_SERVICE)).hasPermission(d))start(d);else message("Acesso USB não autorizado.");}}};

 private final Runnable update=new Runnable(){public void run(){
  if(destroyed)return;CaptureService s=CaptureService.active;boolean running=s!=null;android.content.SharedPreferences prefs=getSharedPreferences("hisho",0);
  connect.setEnabled(!running||s.capturing);connect.setText(!running?"Conectar câmera":s.capturing?"Encerrar captura":"Concluindo edições…");connect.setAlpha(connect.isEnabled()?1:.5f);
  for(View v:new View[]{load,resume,auto,preset,curation,backfill,resolution,curationSensitivity,folderButton})if(v!=null){v.setEnabled(!running);v.setAlpha(running?.45f:1);}if(!running&&curation!=null&&curationSensitivity!=null){curationSensitivity.setEnabled(curation.isChecked());curationSensitivity.setAlpha(curation.isChecked()?1:.45f);}
  if(lockNote!=null)lockNote.setText(running?"Configurações bloqueadas durante a sessão. Encerre a captura para alterar.":"Seus ajustes serão aplicados às próximas fotos.");
  int processed=database.processedCount(),reviews=database.reviewCount(),pending=database.pending();double avg=database.averageScore();String galleryId=prefs.getString("fottoGalleryId","");int[] fs=database.fottoStats(galleryId);
  if(running){status.setText(s.status);originalCount.setText(String.valueOf(s.received));editedCount.setText(String.valueOf(s.edited));pendingCount.setText(String.valueOf(s.pending()));timing.setText(s.detail.isEmpty()?"Aguardando a primeira transferência":s.detail);report.setText(s.report());String connection=s.connectionLabel();badge.setText("●  "+connection);badge.setTextColor("CONECTADA".equals(connection)?SUCCESS:WARNING);centerCamera.setText(s.cameraName+"\n"+prettyConnection(connection));}
  else{status.setText(prefs.getString("lastStatus","Conecte sua câmera para começar."));report.setText(prefs.getString("lastReport","Nenhuma atividade registrada."));originalCount.setText(String.valueOf(prefs.getInt("lastReceived",0)));editedCount.setText(String.valueOf(prefs.getInt("lastEdited",0)));pendingCount.setText(String.valueOf(pending));badge.setText("●  SEM CÂMERA");badge.setTextColor(MUTED);centerCamera.setText("Câmera\nDesconectada");}
  centerCapture.setText("Captura\n"+processed+" processadas"+(pending>0?" · "+pending+" na fila":""));centerCurator.setText("Curadoria\n"+reviews+" em revisão"+(avg>0?" · média "+String.format(Locale.getDefault(),"%.1f/10",avg):""));String event=prefs.getString("fottoGalleryTitle","");centerFotto.setText("Fotto\n"+(FottoApi.token(this).isEmpty()?"Desconectado":(event.isEmpty()?"Conectado · sem evento":fs[0]+" enviadas · "+fs[2]+" pendentes")));
  globalFlowBar.setText((running?"● "+shortCamera(s.cameraName):"○ Câmera")+"   ↓ "+pending+" fila   ✦ "+processed+" prontas   ⚠ "+reviews+" revisão   ↑ "+fs[1]+" enviando");
  updateBackfillBanner(s);refreshGallery();updatePreviewStatus();if(s!=null&&previewState!=null){String live=s.status==null?"":s.status.toLowerCase(Locale.ROOT);if(s.backfillRunning||live.contains("baixando")||live.contains("recebendo")||live.contains("recuperando")){previewState.setText("BAIXANDO");previewState.setBackground(shape(0xdd0b7cff,16));}else if(s.pending()>0&&gallery.follow){previewState.setText("EDITANDO");previewState.setBackground(shape(0xdd0b7cff,16));}}updateFottoStatus();if(selected==1)refreshGalleryQueue(false);if(selected==3)refreshDeliveryQueue(false);handler.postDelayed(this,900);
 }};

 int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}GradientDrawable gradient(int start,int end,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{start,end});d.setCornerRadius(dp(radius));return d;}GradientDrawable border(int color,int radius){GradientDrawable d=shape(color,radius);d.setStroke(dp(1),LINE);return d;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setTypeface(Typeface.create(bold?"sans-serif-medium":"sans-serif",0));return t;}void gap(LinearLayout l,int height){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(height)));}TextView label(LinearLayout p,String value,int size){TextView t=text(value,size,MUTED,false);t.setLineSpacing(dp(3),1);p.addView(t);return t;}
 void heading(LinearLayout p,String eyebrow,String title,String subtitle){TextView e=text(eyebrow,10,BLUE,true);e.setLetterSpacing(.16f);p.addView(e);gap(p,6);p.addView(text(title,27,TEXT,true));gap(p,5);label(p,subtitle,13);gap(p,16);}LinearLayout card(LinearLayout p){LinearLayout c=vertical();c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(border(CARD,18));c.setElevation(dp(1));p.addView(c,new LinearLayout.LayoutParams(-1,-2));return c;}
 Button button(LinearLayout p,String value,View.OnClickListener listener){Button b=new Button(this);b.setText(value);b.setTextSize(13);b.setTextColor(TEXT);b.setAllCaps(false);b.setTypeface(Typeface.create("sans-serif-medium",0));b.setBackground(new RippleDrawable(ColorStateList.valueOf(0x190b7cff),border(0xfffbfcfe,14),null));b.setMinHeight(dp(50));b.setElevation(0);b.setOnClickListener(listener);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.topMargin=dp(8);p.addView(b,lp);return b;}void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(new RippleDrawable(ColorStateList.valueOf(0x22ffffff),gradient(BLUE,0xff0066ff,15),null));}
 CompoundButton toggle(LinearLayout p,String title,String subtitle){LinearLayout r=row(),copy=vertical();copy.addView(text(title,16,TEXT,true));gap(copy,3);label(copy,subtitle,12);r.addView(copy,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(this);sw.setContentDescription(title);sw.setThumbTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{BLUE,0xffaab4c3}));sw.setTrackTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{0xffa9d7ff,0xffd9e0e9}));sw.setChecked(true);r.addView(sw);p.addView(r);return sw;}void sectionLine(LinearLayout p){gap(p,15);View v=new View(this);v.setBackgroundColor(LINE);p.addView(v,new LinearLayout.LayoutParams(-1,dp(1)));gap(p,15);}

 @Override public void onCreate(Bundle b){super.onCreate(b);database=new Jobs(this);if(b!=null){gallery.follow=b.getBoolean("follow",true);gallery.selected=b.getString("photo","");}getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(CARD);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  LinearLayout root=vertical();root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(in.getSystemWindowInsetLeft(),in.getSystemWindowInsetTop(),in.getSystemWindowInsetRight(),in.getSystemWindowInsetBottom());return in.consumeSystemWindowInsets();});setContentView(root);
  LinearLayout header=row();header.setPadding(dp(18),dp(9),dp(18),dp(9));header.setBackgroundColor(CARD);LumoMark logo=new LumoMark(this);header.addView(logo,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout brand=vertical();brand.setPadding(dp(9),0,0,0);brand.addView(text("LUMO",19,TEXT,true));brand.addView(text("FLUXO FOTOGRÁFICO",8,MUTED,true));header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));badge=text("●  PRONTO",10,BLUE,true);badge.setPadding(dp(9),dp(7),dp(9),dp(7));badge.setBackground(shape(0xffeaf4ff,18));header.addView(badge);root.addView(header);
  globalFlowBar=text("○ Câmera   ↓ 0 fila   ✦ 0 prontas   ⚠ 0 revisão   ↑ 0 enviando",10,MUTED,true);globalFlowBar.setSingleLine(true);globalFlowBar.setPadding(dp(18),dp(7),dp(18),dp(7));globalFlowBar.setBackgroundColor(0xfff0f4f9);root.addView(globalFlowBar,new LinearLayout.LayoutParams(-1,dp(31)));
  FrameLayout content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));for(int i=0;i<4;i++){scrollers[i]=new ScrollView(this);scrollers[i].setFillViewport(true);scrollers[i].setVerticalScrollBarEnabled(false);pages[i]=vertical();pages[i].setPadding(dp(18),dp(14),dp(18),dp(22));scrollers[i].addView(pages[i]);content.addView(scrollers[i],new FrameLayout.LayoutParams(-1,-1));}
  capturePage();filesPage();editPage();fottoPage();
  LinearLayout nav=row();nav.setPadding(dp(10),dp(7),dp(10),dp(7));nav.setBackgroundColor(CARD);String[] names={"Captura","Galeria","Editar","Entrega"};for(int i=0;i<4;i++){final int page=i;Button t=new Button(this);t.setText(names[i]);t.setTextSize(12);t.setAllCaps(false);t.setOnClickListener(v->select(page));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1);lp.setMargins(dp(2),0,dp(2),0);nav.addView(t,lp);tabs[i]=t;}root.addView(nav);select(b==null?0:b.getInt("page",0));
  IntentFilter filter=new IntentFilter(USB);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,filter);registered=true;if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},20);
 }

 void select(int page){if(page<0||page>=4)page=0;selected=page;for(int i=0;i<4;i++){scrollers[i].setVisibility(i==page?View.VISIBLE:View.GONE);tabs[i].setTextColor(i==page?BLUE:MUTED);tabs[i].setBackground(shape(i==page?0xffeaf4ff:CARD,13));}if(page==1)refreshGalleryQueue(true);if(page==3){updateFottoStatus();refreshDeliveryQueue(true);if(fottoGalleries.isEmpty()&&!FottoApi.token(this).isEmpty())loadFottoGalleries();}}

 void capturePage(){LinearLayout p=pages[0];heading(p,"CENTRAL DE TRABALHO","Tudo sob controle.","Veja câmera, processamento, curadoria e entrega sem sair da captura.");
  LinearLayout r1=row(),r2=row();p.addView(r1);p.addView(r2);centerCamera=statusCard(r1,"CÂMERA","Câmera\nDesconectada",BLUE);centerCapture=statusCard(r1,"CAPTURA","Captura\n0 processadas",BLUE);centerCurator=statusCard(r2,"CURADORIA","Curadoria\n0 em revisão",WARNING);centerFotto=statusCard(r2,"FOTTO","Fotto\nDesconectado",SUCCESS);gap(p,10);
  backfillBanner=vertical();backfillBanner.setPadding(dp(14),dp(12),dp(14),dp(12));backfillBanner.setBackground(border(0xfffff8eb,15));backfillBannerText=text("",13,TEXT,true);backfillBanner.addView(backfillBannerText);LinearLayout br=row();backfillDownload=miniButton("Baixar agora",v->{CaptureService s=CaptureService.active;if(s!=null)s.approveBackfill();});br.addView(backfillDownload,new LinearLayout.LayoutParams(0,dp(42),1));backfillIgnore=miniButton("Ignorar",v->{CaptureService s=CaptureService.active;if(s!=null)s.ignoreBackfill();});br.addView(backfillIgnore,new LinearLayout.LayoutParams(0,dp(42),1));backfillBanner.addView(br);backfillBanner.setVisibility(View.GONE);p.addView(backfillBanner);
  gap(p,10);previewFrame=new FrameLayout(this);previewFrame.setBackground(border(DARK,22));previewFrame.setClipToOutline(true);p.addView(previewFrame,new LinearLayout.LayoutParams(-1,dp(getResources().getConfiguration().screenWidthDp>=720?500:430)));
  preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setContentDescription("Foto selecionada. Toque para ampliar.");FrameLayout.LayoutParams imageArea=new FrameLayout.LayoutParams(-1,-1);imageArea.bottomMargin=dp(58);previewFrame.addView(preview,imageArea);preview.setOnClickListener(v->fullscreen());
  empty=vertical();empty.setGravity(Gravity.CENTER);empty.setPadding(dp(20),dp(20),dp(20),dp(20));previewFrame.addView(empty,new FrameLayout.LayoutParams(-1,-1));View art=new CameraArt(this);empty.addView(art,new LinearLayout.LayoutParams(dp(110),dp(100)));gap(empty,12);empty.addView(text("Pronta para a próxima foto",17,Color.WHITE,true));gap(empty,6);TextView note=text("Conecte sua Canon. A foto editada aparece aqui automaticamente.",12,0xffcbd5e1,false);note.setGravity(Gravity.CENTER);empty.addView(note);
  previewState=text("AGUARDANDO",10,Color.WHITE,true);previewState.setPadding(dp(9),dp(6),dp(9),dp(6));previewState.setBackground(shape(0xaa0b1220,16));FrameLayout.LayoutParams sp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.LEFT);sp.setMargins(dp(12),dp(12),0,0);previewFrame.addView(previewState,sp);previewScore=text("",11,Color.WHITE,true);previewScore.setPadding(dp(9),dp(6),dp(9),dp(6));previewScore.setBackground(shape(0xaa0b7cff,16));FrameLayout.LayoutParams qp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.RIGHT);qp.setMargins(0,dp(12),dp(12),0);previewFrame.addView(previewScore,qp);
  LinearLayout footer=vertical();footer.setPadding(dp(14),dp(10),dp(14),dp(10));footer.setBackgroundColor(0xdc0b1012);previewFrame.addView(footer,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));previewTitle=text("LIVE PREVIEW",10,CYAN,true);footer.addView(previewTitle);previewSub=text("Original preservado · processamento em segundo plano",12,Color.WHITE,false);footer.addView(previewSub);
  gap(p,9);filmScroll=new HorizontalScrollView(this);filmScroll.setHorizontalScrollBarEnabled(false);filmStrip=row();filmScroll.addView(filmStrip);p.addView(filmScroll,new LinearLayout.LayoutParams(-1,dp(82)));LinearLayout navigation=row();p.addView(navigation);previousPhoto=galleryButton(navigation,"‹",v->movePhoto(-1));livePhoto=galleryButton(navigation,"Acompanhar novas",v->{gallery.followLatest();showSelection(true);});nextPhoto=galleryButton(navigation,"›",v->movePhoto(1));galleryInfo=label(p,"As miniaturas aparecem quando o processamento termina.",11);
  gap(p,10);LinearLayout stats=row();originalCount=stat(stats,"RECEBIDAS");editedCount=stat(stats,"APROVADAS");pendingCount=stat(stats,"NA FILA");p.addView(stats);gap(p,10);status=text("Conecte sua câmera para começar.",14,TEXT,true);p.addView(status);gap(p,4);timing=label(p,"Recebimento e edição em filas independentes",11);connect=button(p,"Conectar câmera",v->{CaptureService s=CaptureService.active;if(s!=null){if(s.capturing)new AlertDialog.Builder(this).setTitle("Encerrar captura?").setMessage("A foto em andamento e as edições pendentes serão concluídas.").setPositiveButton("Encerrar",(d,n)->startService(new Intent(this,CaptureService.class).setAction("stop"))).setNegativeButton("Continuar",null).show();}else chooseTransport();});primary(connect);
  Button settingsButton=button(p,"Configurações da captura",v->{captureSettingsPanel.setVisibility(captureSettingsPanel.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);});captureSettingsPanel=vertical();captureSettingsPanel.setVisibility(View.GONE);p.addView(captureSettingsPanel);resume=button(captureSettingsPanel,"Retomar edições pendentes",v->start(null));LinearLayout recovery=card(captureSettingsPanel);backfill=toggle(recovery,"Recuperar fotos não baixadas","Ao reconectar, compara o cartão com o histórico do LUMO.");android.content.SharedPreferences cp=getSharedPreferences("hisho",0);backfill.setChecked(cp.getBoolean("backfillEnabled",true));backfill.setOnCheckedChangeListener((b,checked)->cp.edit().putBoolean("backfillEnabled",checked).apply());gap(recovery,7);label(recovery,"Quando houver retroativas, o LUMO mostra um banner discreto. A captura ao vivo continua normalmente até você tocar em Baixar agora.",11);gap(captureSettingsPanel,8);label(captureSettingsPanel,"USB · R8 / SL2 | Wi‑Fi experimental",11);report=text("",10,MUTED,false);report.setVisibility(View.GONE);captureSettingsPanel.addView(report);
 }

 TextView statusCard(LinearLayout parent,String title,String value,int accent){LinearLayout c=vertical();c.setPadding(dp(12),dp(11),dp(12),dp(11));c.setBackground(border(CARD,15));TextView t=text(title,9,accent,true);c.addView(t);gap(c,5);TextView v=text(value,13,TEXT,true);c.addView(v);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));parent.addView(c,lp);return v;}
 TextView stat(LinearLayout row,String title){LinearLayout c=vertical();c.setPadding(dp(11),dp(11),dp(7),dp(11));c.setBackground(border(CARD,14));TextView n=text("0",24,TEXT,true);c.addView(n);gap(c,3);c.addView(text(title,8,MUTED,true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.rightMargin=dp(4);row.addView(c,lp);return n;}
 Button miniButton(String title,View.OnClickListener listener){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextSize(11);b.setTextColor(TEXT);b.setBackground(border(CARD,11));b.setOnClickListener(listener);return b;}
 String prettyConnection(String s){if("CONECTADA".equals(s))return "Conectada";if("OCUPADA".equals(s))return "Ocupada";return s==null?"Desconectada":s;}
 String shortCamera(String name){if(name==null||name.isEmpty())return "Canon";return name.length()>12?name.substring(0,12):name;}
 void updateBackfillBanner(CaptureService s){if(backfillBanner==null)return;if(s==null){backfillBanner.setVisibility(View.GONE);return;}if(s.backfillWaiting){backfillBanner.setVisibility(View.VISIBLE);backfillBannerText.setText("Encontramos "+s.backfillFound+" foto(s) novas na câmera. Elas ainda não foram baixadas.");backfillDownload.setVisibility(View.VISIBLE);backfillIgnore.setVisibility(View.VISIBLE);}else if(s.backfillRunning){backfillBanner.setVisibility(View.VISIBLE);backfillBannerText.setText("Recuperando retroativas · "+s.backfillDone+" / "+s.backfillFound+" · as próximas serão editadas e passarão pela curadoria.");backfillDownload.setVisibility(View.GONE);backfillIgnore.setVisibility(View.GONE);}else backfillBanner.setVisibility(View.GONE);}

 void filesPage(){LinearLayout p=pages[1];heading(p,"GALERIA","Fila visual inteligente.","Filtre por estado, revise problemas e veja a nota técnica de cada foto.");galleryTaskLabel=text("Nenhuma foto para revisar.",14,TEXT,true);galleryTaskLabel.setPadding(dp(13),dp(11),dp(13),dp(11));galleryTaskLabel.setBackground(border(CARD,14));p.addView(galleryTaskLabel);gap(p,10);HorizontalScrollView filters=new HorizontalScrollView(this);filters.setHorizontalScrollBarEnabled(false);LinearLayout rail=row();filters.addView(rail);String[] labels={"Todas","Aprovadas","Revisão","Enviadas","Pendentes"};String[] values={"all","approved","review","sent","pending"};for(int i=0;i<labels.length;i++){final String f=values[i];Button b=miniButton(labels[i],v->{galleryFilter=f;updateFilterButtons();refreshGalleryQueue(true);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(i==4?104:96),dp(42));lp.rightMargin=dp(6);rail.addView(b,lp);galleryFilterButtons[i]=b;}p.addView(filters,new LinearLayout.LayoutParams(-1,dp(48)));updateFilterButtons();gap(p,8);editSelectionLabel=label(p,"Nenhuma foto marcada para edição em lote.",11);galleryQueue=vertical();p.addView(galleryQueue);Button editBatch=button(p,"Editar seleção",v->{if(editSelection.isEmpty())message("Marque as fotos que deseja editar.");else openEditor(editSelection.iterator().next(),new ArrayList<>(editSelection));});primary(editBatch);button(p,"Selecionar as 24 mais recentes",v->selectRecentForEdit());button(p,"Limpar seleção",v->{editSelection.clear();refreshGalleryQueue(true);});button(p,"Diagnóstico da sessão",v->diagnostic());gap(p,12);label(p,"LUMO · Android 0.12.0 · Capturar → Processar → Revisar → Entregar",11);}
 void updateFilterButtons(){String[] values={"all","approved","review","sent","pending"};for(int i=0;i<galleryFilterButtons.length;i++)if(galleryFilterButtons[i]!=null){boolean on=values[i].equals(galleryFilter);galleryFilterButtons[i].setTextColor(on?Color.WHITE:TEXT);galleryFilterButtons[i].setBackground(shape(on?BLUE:CARD,12));}}
 void refreshGalleryQueue(boolean force){if(galleryQueue==null)return;String gid=getSharedPreferences("hisho",0).getString("fottoGalleryId","");int reviews=database.reviewCount();double avg=database.averageScore();galleryTaskLabel.setText(reviews>0?reviews+" para revisar"+(avg>0?" · média técnica "+String.format(Locale.getDefault(),"%.1f/10",avg):""):"Tudo revisado"+(avg>0?" · média técnica "+String.format(Locale.getDefault(),"%.1f/10",avg):""));int[] gst=database.fottoStats(gid);String sig=galleryFilter+":"+gid+":"+database.maxRowId()+":"+reviews+":"+editSelection.size()+":"+Arrays.toString(gst);if(!force&&sig.equals(galleryListSignature))return;galleryListSignature=sig;galleryQueue.removeAllViews();String sql="SELECT j.id,j.name,j.edited,j.original,j.state,COALESCE(j.error,''),j.score,COALESCE(f.state,'pending') FROM jobs j LEFT JOIN fotto_uploads f ON f.job_id=j.id AND f.gallery_id=? ORDER BY j.rowid DESC LIMIT 80";int shown=0;try(Cursor c=database.getReadableDatabase().rawQuery(sql,new String[]{gid})){while(c.moveToNext()){String id=c.getString(0),name=c.getString(1),edited=c.getString(2),original=c.getString(3),state=c.getString(4),reason=c.getString(5),upload=c.getString(7);int score=c.getInt(6);if(!matchesFilter(state,upload))continue;addGalleryRow(id,name,edited,original,state,reason,score,upload);shown++;if(shown>=36)break;}}if(shown==0){gap(galleryQueue,16);label(galleryQueue,"Nenhuma foto neste filtro.",13);}updateEditSelectionLabel();}
 boolean matchesFilter(String state,String upload){if("approved".equals(galleryFilter))return "done".equals(state);if("review".equals(galleryFilter))return "review".equals(state);if("sent".equals(galleryFilter))return "done".equals(state)&&"done".equals(upload);if("pending".equals(galleryFilter))return !"review".equals(state)&&(!"done".equals(state)||!"done".equals(upload));return true;}
 void addGalleryRow(String id,String name,String edited,String original,String state,String reason,int score,String upload){LinearLayout box=row();box.setPadding(dp(9),dp(9),dp(9),dp(9));int bg="review".equals(state)?0xfffffbf5:"error".equals(state)?0xfffff5f5:CARD;box.setBackground(border(bg,15));galleryQueue.addView(box,new LinearLayout.LayoutParams(-1,-2));ImageView thumb=new ImageView(this);thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);thumb.setBackground(shape(0xffedf1f6,11));box.addView(thumb,new LinearLayout.LayoutParams(dp(76),dp(76)));String raw=(edited!=null&&!edited.isEmpty())?edited:original;if(raw!=null&&!raw.isEmpty()){Bitmap cached=thumbCache.get(raw);if(cached!=null)thumb.setImageBitmap(cached);else thumbnails.execute(()->{Bitmap b=decodeImage(raw,160);handler.post(()->{if(!destroyed&&b!=null){thumbCache.put(raw,b);thumb.setImageBitmap(b);}});});}
  LinearLayout info=vertical();info.setPadding(dp(10),0,dp(5),0);box.addView(info,new LinearLayout.LayoutParams(0,-2,1));info.addView(text(displayName(name,state),12,TEXT,true));gap(info,3);LinearLayout chips=row();TextView st=chip(statusLabel(state,upload),statusColor(state,upload));chips.addView(st);if(score>0){TextView sc=chip(score+"/10",scoreColor(score));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(28));cp.leftMargin=dp(5);chips.addView(sc,cp);}info.addView(chips);if("review".equals(state)&&reason!=null&&!reason.isEmpty()){gap(info,4);TextView why=text(reason,10,MUTED,false);why.setMaxLines(2);info.addView(why);}LinearLayout acts=row();CheckBox mark=new CheckBox(this);mark.setChecked(editSelection.contains(id));mark.setContentDescription("Selecionar "+name);mark.setOnCheckedChangeListener((b,checked)->{if(checked)editSelection.add(id);else editSelection.remove(id);updateEditSelectionLabel();});acts.addView(mark,new LinearLayout.LayoutParams(dp(42),dp(42)));Button edit=miniButton("Editar",v->openEditor(id,editSelection.isEmpty()?Collections.singletonList(id):new ArrayList<>(editSelection)));acts.addView(edit,new LinearLayout.LayoutParams(0,dp(40),1));if("review".equals(state)){Button approve=miniButton("Aprovar",v->approveReview(id,name,edited));approve.setTextColor(WARNING);acts.addView(approve,new LinearLayout.LayoutParams(0,dp(40),1));}info.addView(acts);if(raw!=null&&!raw.isEmpty())thumb.setOnClickListener(v->openImage(raw));gap(galleryQueue,7);}
 TextView chip(String s,int color){TextView t=text(s,9,color,true);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),0,dp(8),0);t.setBackground(shape(color==WARNING?0xfffff2dd:color==SUCCESS?0xffe8f7ef:color==ERROR?0xffffeded:0xffeaf4ff,14));return t;}int scoreColor(int score){return score>=8?SUCCESS:score>=5?WARNING:ERROR;}String displayName(String name,String state){if(name==null)return "Foto";return name.replaceFirst("(?i)\\.jpg$","review".equals(state)?"_REVISAO.jpg":"_Editada.jpg");}
 String statusLabel(String state,String upload){if("review".equals(state))return "REVISÃO";if("error".equals(state)||"originalError".equals(state))return "FALHA";if("editing".equals(state)||"ready".equals(state)||"original".equals(state))return "PROCESSANDO";if("done".equals(state)){if("done".equals(upload))return "ENVIADA";if("uploading".equals(upload))return "ENVIANDO";if("error".equals(upload))return "FALHA ENVIO";return "APROVADA";}return state.toUpperCase(Locale.ROOT);}int statusColor(String state,String upload){String l=statusLabel(state,upload);return l.contains("FALHA")?ERROR:l.equals("REVISÃO")?WARNING:l.equals("ENVIADA")?SUCCESS:BLUE;}

 void editPage(){LinearLayout p=pages[2];heading(p,"EDITAR","Seu estilo, com controle.","Auto e Preset montam a base; o editor manual refina sem destruir o original.");LinearLayout c=card(p);auto=toggle(c,"Correção automática","Ajustes leves de luminosidade e cor.");sectionLine(c);preset=toggle(c,"Seu preset","Aplique seu estilo após a correção.");gap(p,12);LinearLayout style=card(p);style.addView(text("ESTILO DA SESSÃO",10,BLUE,true));gap(style,8);presetLabel=text("Vibrant",22,TEXT,true);style.addView(presetLabel);gap(style,5);label(style,"Preset XMP · interpretação aproximada",11);try{String saved=getSharedPreferences("hisho",0).getString("preset",null);presetData=new JSONObject(saved==null?read(getAssets().open("vibrant.json")):saved);presetName=getSharedPreferences("hisho",0).getString("presetName","Vibrant");presetLabel.setText(presetName);}catch(Exception e){presetData=new JSONObject();message("Falha ao ler preset: "+e.getMessage());}load=button(style,"Importar outro preset",v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),10));
  gap(p,12);LinearLayout manual=card(p);manual.addView(text("EDITOR FOTOGRÁFICO",10,BLUE,true));gap(manual,7);manual.addView(text("Refinar Auto + Preset",17,TEXT,true));gap(manual,4);label(manual,"Prévia contínua, Antes/Depois, filmstrip e sincronização seletiva em lote.",11);Button currentEdit=button(manual,"Editar foto selecionada",v->{String id=currentGalleryJobId();if(id.isEmpty())message("Selecione uma foto na Captura ou na Galeria.");else openEditor(id,Collections.singletonList(id));});primary(currentEdit);button(manual,"Editar seleção da Galeria",v->{if(editSelection.isEmpty())message("Marque fotos na Galeria.");else openEditor(editSelection.iterator().next(),new ArrayList<>(editSelection));});
  gap(p,12);LinearLayout quality=card(p);quality.addView(text("Tamanho da cópia editada",16,TEXT,true));gap(quality,8);resolution=new Spinner(this);String[] modes={"Rápida · 2560 px","Mais rápida · 1920 px","Resolução original"};resolution.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,modes));android.content.SharedPreferences settings=getSharedPreferences("hisho",0);auto.setChecked(settings.getBoolean("autoEnabled",true));preset.setChecked(settings.getBoolean("presetEnabled",true));resolution.setSelection(Math.max(0,Math.min(2,settings.getInt("resolution",0))));auto.setOnCheckedChangeListener((b,checked)->settings.edit().putBoolean("autoEnabled",checked).apply());preset.setOnCheckedChangeListener((b,checked)->settings.edit().putBoolean("presetEnabled",checked).apply());resolution.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> parent,View view,int pos,long id){settings.edit().putInt("resolution",pos).apply();}public void onNothingSelected(android.widget.AdapterView<?> parent){}});quality.addView(resolution,new LinearLayout.LayoutParams(-1,dp(50)));
  gap(p,12);LinearLayout curateCard=card(p);curation=toggle(curateCard,"Curadoria automática","Bloqueia fotos tecnicamente suspeitas antes da entrega.");sectionLine(curateCard);curateCard.addView(text("Sensibilidade",16,TEXT,true));gap(curateCard,7);curationSensitivity=new Spinner(this);String[] curateModes={"Baixa · só falhas evidentes","Média · equilíbrio recomendado","Alta · revisão mais rigorosa"};curationSensitivity.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,curateModes));curateCard.addView(curationSensitivity,new LinearLayout.LayoutParams(-1,dp(50)));label(curateCard,"Toda foto recebe uma nota técnica de 1 a 10. A sensibilidade muda o limiar de revisão, não a nota.",11);curation.setChecked(settings.getBoolean("curationEnabled",true));curationSensitivity.setSelection(Math.max(0,Math.min(2,settings.getInt("curationSensitivity",1))));curationSensitivity.setEnabled(curation.isChecked());curation.setOnCheckedChangeListener((b,checked)->{settings.edit().putBoolean("curationEnabled",checked).apply();curationSensitivity.setEnabled(checked);curationSensitivity.setAlpha(checked?1:.45f);});curationSensitivity.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> parent,View view,int pos,long id){settings.edit().putInt("curationSensitivity",pos).apply();}public void onNothingSelected(android.widget.AdapterView<?> parent){}});
  gap(p,12);LinearLayout alerts=card(p);CompoundButton sound=toggle(alerts,"Som de desconexão","Aviso quando a conexão ativa cair.");sound.setChecked(settings.getBoolean("disconnectSound",true));sound.setOnCheckedChangeListener((b,checked)->settings.edit().putBoolean("disconnectSound",checked).apply());button(alerts,"Testar alerta",v->DisconnectAlert.test(this));gap(p,14);lockNote=label(p,"Seus ajustes serão aplicados às próximas fotos.",12);button(p,"Sobre a edição XMP",v->new AlertDialog.Builder(this).setTitle("Seu preset no LUMO").setMessage("Ajustes de luz, exposição, contraste, HSL, clareza, nitidez e vinheta são adaptados ao JPEG. Perfis Adobe, máscaras, curvas e redução de ruído não são reproduzidos.").setPositiveButton("Entendi",null).show());
 }

 void fottoPage(){LinearLayout p=pages[3];heading(p,"ENTREGA","Fila de upload clara.","Veja o que foi enviado, o que está na fila e o que precisa de nova tentativa.");deliveryHeader=text("Fotto · Desconectado",16,TEXT,true);deliveryHeader.setPadding(dp(14),dp(12),dp(14),dp(12));deliveryHeader.setBackground(border(CARD,15));p.addView(deliveryHeader);gap(p,10);LinearLayout stat=row();deliveryDone=deliveryStat(stat,"ENVIADAS",SUCCESS);deliveryUploading=deliveryStat(stat,"ENVIANDO",BLUE);deliveryPending=deliveryStat(stat,"PENDENTES",WARNING);deliveryFailed=deliveryStat(stat,"FALHAS",ERROR);p.addView(stat);gap(p,10);deliveryQueue=vertical();p.addView(deliveryQueue);Button settings=button(p,"Configurações da entrega",v->{deliverySettingsPanel.setVisibility(deliverySettingsPanel.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);});deliverySettingsPanel=vertical();deliverySettingsPanel.setVisibility(View.GONE);p.addView(deliverySettingsPanel);
  LinearLayout dest=card(deliverySettingsPanel);dest.addView(text("Pasta de exportação",17,TEXT,true));gap(dest,5);folderLabel=label(dest,"",12);folderButton=button(dest,"Selecionar pasta",v->chooseExportFolder());updateExportFolder();gap(deliverySettingsPanel,10);LinearLayout auth=card(deliverySettingsPanel);auth.addView(text("Conta Fotto",17,TEXT,true));gap(auth,5);fottoStatus=label(auth,"Não conectado.",12);fottoConnect=button(auth,"Conectar com Fotto",v->startActivityForResult(new Intent(this,FottoLoginActivity.class),30));gap(deliverySettingsPanel,10);LinearLayout event=card(deliverySettingsPanel);event.addView(text("Evento de destino",17,TEXT,true));gap(event,6);fottoEvents=new Spinner(this);event.addView(fottoEvents,new LinearLayout.LayoutParams(-1,dp(50)));fottoEvents.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> parent,View view,int pos,long id){if(settingFottoEvents||pos<0||pos>=fottoGalleries.size())return;FottoApi.Gallery g=fottoGalleries.get(pos);android.content.SharedPreferences prefs=getSharedPreferences("hisho",0);String old=prefs.getString("fottoGalleryId","");android.content.SharedPreferences.Editor e=prefs.edit().putString("fottoGalleryId",g.id).putString("fottoGalleryTitle",g.title);if(!g.id.equals(old)&&prefs.getBoolean("fottoAuto",false))e.putLong("fottoStartRowid",database.maxRowId());e.apply();deliverySignature="";updateFottoStatus();refreshDeliveryQueue(true);}public void onNothingSelected(android.widget.AdapterView<?> parent){}});fottoRefresh=button(event,"Atualizar eventos",v->loadFottoGalleries());gap(deliverySettingsPanel,10);LinearLayout monitor=card(deliverySettingsPanel);fottoSourceLabel=label(monitor,"",12);gap(monitor,10);fottoAuto=toggle(monitor,"Envio automático","Toda nova aprovada será enviada ao evento selecionado.");android.content.SharedPreferences prefs=getSharedPreferences("hisho",0);fottoAuto.setChecked(prefs.getBoolean("fottoAuto",false));bindFottoToggle();fottoUploadStatus=label(monitor,"",12);fottoSend=button(monitor,"Enviar aprovadas já existentes",v->{if(FottoApi.token(this).isEmpty()||prefs.getString("fottoGalleryId","").isEmpty()){message("Conecte o Fotto e escolha o evento primeiro.");return;}FottoSync.sendExisting(this);prefs.edit().putString("fottoLastStatus","Procurando Editadas para enviar…").apply();updateFottoStatus();});updateFottoStatus();if(!FottoApi.token(this).isEmpty())loadFottoGalleries();FottoSync.kick(this);
 }
 TextView deliveryStat(LinearLayout parent,String title,int color){LinearLayout c=vertical();c.setPadding(dp(8),dp(10),dp(8),dp(10));c.setBackground(border(CARD,13));TextView n=text("0",20,color,true);n.setGravity(Gravity.CENTER);c.addView(n);TextView t=text(title,7,MUTED,true);t.setGravity(Gravity.CENTER);c.addView(t);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(2),0,dp(2),0);parent.addView(c,lp);return n;}
 void refreshDeliveryQueue(boolean force){if(deliveryQueue==null)return;String gid=getSharedPreferences("hisho",0).getString("fottoGalleryId","");int[] st=database.fottoStats(gid);deliveryDone.setText(String.valueOf(st[0]));deliveryUploading.setText(String.valueOf(st[1]));deliveryPending.setText(String.valueOf(st[2]));deliveryFailed.setText(String.valueOf(st[3]));String title=getSharedPreferences("hisho",0).getString("fottoGalleryTitle","");deliveryHeader.setText(FottoApi.token(this).isEmpty()?"Fotto · Desconectado":"Fotto · Conectado"+(title.isEmpty()?" · selecione um evento":" · Evento: "+title));String sig=gid+":"+Arrays.toString(st)+":"+database.maxRowId()+":"+FottoSync.running();if(!force&&sig.equals(deliverySignature))return;deliverySignature=sig;deliveryQueue.removeAllViews();if(gid.isEmpty()){label(deliveryQueue,"Escolha um evento em Configurações da entrega.",12);return;}String sql="SELECT j.id,j.name,j.edited,j.score,COALESCE(f.state,'pending'),COALESCE(f.error,'') FROM jobs j LEFT JOIN fotto_uploads f ON f.job_id=j.id AND f.gallery_id=? WHERE j.state='done' AND j.edited IS NOT NULL ORDER BY j.rowid DESC LIMIT 24";int count=0;try(Cursor c=database.getReadableDatabase().rawQuery(sql,new String[]{gid})){while(c.moveToNext()){String id=c.getString(0),name=c.getString(1),uri=c.getString(2),state=c.getString(4),err=c.getString(5);int score=c.getInt(3);LinearLayout box=vertical();box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(border(CARD,14));deliveryQueue.addView(box);LinearLayout top=row();TextView nm=text(name.replaceFirst("(?i)\\.jpg$","_Editada.jpg"),11,TEXT,true);top.addView(nm,new LinearLayout.LayoutParams(0,-2,1));top.addView(chip(score>0?score+"/10":"—",score>0?scoreColor(score):MUTED));box.addView(top);gap(box,4);TextView progress=text(uploadText(state),11,statusColor("done",state),true);box.addView(progress);if("error".equals(state)){TextView er=text(err,10,MUTED,false);er.setMaxLines(2);box.addView(er);Button retry=button(box,"Tentar novamente",v->{database.fottoRetryOne(id,gid);FottoSync.sendExisting(this);deliverySignature="";refreshDeliveryQueue(true);});retry.setTextColor(ERROR);}else if("pending".equals(state)){TextView q=text("Aguardando vez na fila",10,MUTED,false);box.addView(q);}else if("uploading".equals(state)){ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setIndeterminate(true);box.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));}gap(deliveryQueue,6);count++;}}if(count==0)label(deliveryQueue,"Nenhuma foto aprovada para este evento ainda.",12);}
 String uploadText(String s){if("done".equals(s))return "Enviada ao Fotto";if("uploading".equals(s))return "Enviando agora…";if("error".equals(s))return "Falha no envio";return "Pendente";}

 void chooseExportFolder(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);startActivityForResult(i,20);}void updateExportFolder(){if(folderLabel==null)return;String raw=getSharedPreferences("hisho",0).getString("exportTreeUri","");if(raw.isEmpty()){folderLabel.setText("Padrão · Pictures / LUMO");if(folderButton!=null)folderButton.setText("Selecionar pasta");return;}Uri uri=Uri.parse(raw);String name=uri.getLastPathSegment();if(name==null||name.isEmpty())name=raw;try{name=java.net.URLDecoder.decode(name,"UTF-8");}catch(Exception ignored){}int colon=name.lastIndexOf(':');if(colon>=0&&colon+1<name.length())name=name.substring(colon+1);folderLabel.setText("Selecionada · "+name);if(folderButton!=null)folderButton.setText("Alterar pasta");}
 String exportRootLabel(){String raw=getSharedPreferences("hisho",0).getString("exportTreeUri","");if(raw.isEmpty())return "Pictures / LUMO";Uri uri=Uri.parse(raw);String name=uri.getLastPathSegment();if(name==null||name.isEmpty())name=raw;try{name=java.net.URLDecoder.decode(name,"UTF-8");}catch(Exception ignored){}int colon=name.lastIndexOf(':');if(colon>=0&&colon+1<name.length())name=name.substring(colon+1);return name;}
 void updateFottoStatus(){if(fottoStatus==null)return;android.content.SharedPreferences prefs=getSharedPreferences("hisho",0);String token=FottoApi.token(this),galleryTitle=prefs.getString("fottoGalleryTitle","");boolean active=prefs.getBoolean("fottoAuto",false);fottoStatus.setText(token.isEmpty()?"Não conectado.":"Sessão conectada"+(galleryTitle.isEmpty()?" · escolha um evento":" · "+galleryTitle));if(fottoConnect!=null)fottoConnect.setText(token.isEmpty()?"Conectar com Fotto":"Reconectar conta Fotto");if(fottoSourceLabel!=null)fottoSourceLabel.setText("Origem · "+exportRootLabel()+" / Editadas");String last=prefs.getString("fottoLastStatus",active?"Monitor ativo. Aguardando novas Editadas.":"Monitor desligado.");if(FottoSync.running())last="Enviando para o Fotto…";if(fottoUploadStatus!=null)fottoUploadStatus.setText(last);if(fottoAuto!=null&&fottoAuto.isChecked()!=active){fottoAuto.setOnCheckedChangeListener(null);fottoAuto.setChecked(active);bindFottoToggle();}}
 void bindFottoToggle(){if(fottoAuto==null)return;fottoAuto.setOnCheckedChangeListener((b,checked)->{if(checked){if(FottoApi.token(this).isEmpty()){message("Conecte sua conta Fotto antes de ativar o envio automático.");getSharedPreferences("hisho",0).edit().putBoolean("fottoAuto",false).apply();b.setChecked(false);return;}String galleryId=getSharedPreferences("hisho",0).getString("fottoGalleryId","");if(galleryId.isEmpty()){message("Escolha um evento Fotto antes de ativar o envio automático.");getSharedPreferences("hisho",0).edit().putBoolean("fottoAuto",false).apply();b.setChecked(false);return;}getSharedPreferences("hisho",0).edit().putBoolean("fottoAuto",true).putLong("fottoStartRowid",database.maxRowId()).putString("fottoLastStatus","Monitor ativo. Aguardando novas Editadas.").apply();FottoSync.kick(this);}else getSharedPreferences("hisho",0).edit().putBoolean("fottoAuto",false).putString("fottoLastStatus","Monitor Fotto pausado.").apply();updateFottoStatus();});}
 void loadFottoGalleries(){if(fottoEvents==null)return;if(FottoApi.token(this).isEmpty()){updateFottoStatus();return;}fottoStatus.setText("Carregando eventos…");fottoRefresh.setEnabled(false);fottoNetwork.execute(()->{try{ArrayList<FottoApi.Gallery> list=FottoApi.galleries(this);handler.post(()->{if(destroyed)return;fottoGalleries.clear();fottoGalleries.addAll(list);settingFottoEvents=true;fottoEvents.setAdapter(new ArrayAdapter<FottoApi.Gallery>(this,android.R.layout.simple_spinner_dropdown_item,fottoGalleries));String saved=getSharedPreferences("hisho",0).getString("fottoGalleryId","");int choice=-1;for(int i=0;i<fottoGalleries.size();i++)if(fottoGalleries.get(i).id.equals(saved)){choice=i;break;}if(choice<0&&!fottoGalleries.isEmpty()){choice=0;FottoApi.Gallery g=fottoGalleries.get(0);getSharedPreferences("hisho",0).edit().putString("fottoGalleryId",g.id).putString("fottoGalleryTitle",g.title).apply();}if(choice>=0)fottoEvents.setSelection(choice);settingFottoEvents=false;fottoRefresh.setEnabled(true);if(list.isEmpty())getSharedPreferences("hisho",0).edit().putString("fottoLastStatus","Nenhum evento encontrado nesta conta.").apply();updateFottoStatus();refreshDeliveryQueue(true);});}catch(Exception e){handler.post(()->{if(destroyed)return;fottoRefresh.setEnabled(true);getSharedPreferences("hisho",0).edit().putString("fottoLastStatus","Falha ao carregar eventos · "+e.getMessage()).apply();updateFottoStatus();});}});}

 void selectRecentForEdit(){editSelection.clear();try(Cursor c=database.getReadableDatabase().rawQuery("SELECT id FROM jobs WHERE state IN ('done','review') ORDER BY rowid DESC LIMIT 24",null)){while(c.moveToNext())editSelection.add(c.getString(0));}refreshGalleryQueue(true);}void updateEditSelectionLabel(){if(editSelectionLabel!=null)editSelectionLabel.setText(editSelection.isEmpty()?"Nenhuma foto marcada para edição em lote.":editSelection.size()+" foto(s) marcada(s) · use Editar seleção ou abra uma delas.");}
 String currentGalleryJobId(){return gallery.selected==null||gallery.selected.isEmpty()?"":database.idForEdited(gallery.selected);}void openEditor(String focusId,Collection<String> ids){if(focusId==null||focusId.isEmpty()){message("Foto não encontrada no histórico.");return;}LinkedHashSet<String> unique=new LinkedHashSet<>();if(ids!=null)unique.addAll(ids);unique.add(focusId);StringBuilder packed=new StringBuilder();for(String id:unique){if(packed.length()>0)packed.append(',');packed.append(id);}startActivity(new Intent(this,ManualEditorActivity.class).putExtra("focusId",focusId).putExtra("jobIds",packed.toString()));}
 void approveReview(String id,String name,String reviewUri){if(reviewUri==null||reviewUri.isEmpty()){message("Foto de revisão indisponível.");return;}message("Aprovando foto para entrega…");images.execute(()->{File tmp=new File(getCacheDir(),"approve_"+id+".jpg");boolean cleared=false;try(InputStream in=getContentResolver().openInputStream(Uri.parse(reviewUri));OutputStream out=new FileOutputStream(tmp)){if(in==null)throw new IOException("Foto de revisão indisponível.");Jobs.copy(in,out);database.clearEdited(id);cleared=true;database.save(tmp,"Editadas",name.replaceFirst("(?i)\\.jpg$","_Editada.jpg"),id,"edited");database.set(id,"done","error",null);try{getContentResolver().delete(Uri.parse(reviewUri),null,null);}catch(Exception ignored){}FottoSync.kick(this);handler.post(()->{gallerySignature="";galleryListSignature="";refreshGalleryQueue(true);refreshGallery();message("Foto aprovada. Agora ela pode entrar na fila de entrega.");});}catch(Exception e){if(cleared)database.set(id,"review","edited",reviewUri);handler.post(()->message("Não foi possível aprovar: "+e.getMessage()));}finally{tmp.delete();}});}
 void openImage(String uri){try{startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(Uri.parse(uri),"image/jpeg").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(Exception e){message("Não foi possível abrir. Confira o arquivo na Galeria.");}}void diagnostic(){TextView t=text(report==null?"":report.getText().toString(),12,MUTED,false);t.setTextIsSelectable(true);t.setPadding(dp(16),dp(16),dp(16),dp(16));ScrollView scroll=new ScrollView(this);scroll.addView(t);new AlertDialog.Builder(this).setTitle("Diagnóstico da sessão").setView(scroll).setPositiveButton("Copiar",(d,n)->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("LUMO",t.getText()));message("Diagnóstico copiado.");}).setNegativeButton("Fechar",null).show();}
 Button galleryButton(LinearLayout parent,String title,View.OnClickListener listener){Button b=miniButton(title,listener);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(title.length()>1?0:dp(48),dp(42),title.length()>1?1:0);lp.setMargins(dp(3),dp(6),dp(3),dp(6));parent.addView(b,lp);return b;}

 void refreshGallery(){ArrayList<GallerySelection.Photo> list=new ArrayList<>();StringBuilder signature=new StringBuilder();photoStates.clear();photoScores.clear();try(Cursor c=database.getReadableDatabase().rawQuery("SELECT name,edited,state,score FROM jobs WHERE state IN ('done','review') AND edited IS NOT NULL ORDER BY rowid DESC LIMIT 60",null)){while(c.moveToNext()){String uri=c.getString(1),state=c.getString(2);int score=c.getInt(3);list.add(new GallerySelection.Photo(uri,c.getString(0)));photoStates.put(uri,state);photoScores.put(uri,score);signature.append(uri).append(':').append(state).append(':').append(score).append(';');}}if(signature.toString().equals(gallerySignature)){showSelection(false);return;}gallerySignature=signature.toString();Collections.reverse(list);gallery.replace(list);final long generation=++stripGeneration;filmStrip.removeAllViews();tiles.clear();for(GallerySelection.Photo photo:gallery.photos){FrameLayout tile=new FrameLayout(this);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(76),dp(76));lp.rightMargin=dp(6);filmStrip.addView(tile,lp);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(shape(CARD,10));image.setClipToOutline(true);tile.addView(image,new FrameLayout.LayoutParams(-1,-1));String st=photoStates.get(photo.uri);if("review".equals(st)){TextView flag=text("!",10,Color.WHITE,true);flag.setGravity(Gravity.CENTER);flag.setBackground(shape(WARNING,12));tile.addView(flag,new FrameLayout.LayoutParams(dp(22),dp(22),Gravity.TOP|Gravity.RIGHT));}tile.setOnClickListener(v->{gallery.select(photo.uri);showSelection(true);});tiles.put(photo.uri,tile);Bitmap cached=thumbCache.get(photo.uri);if(cached!=null)image.setImageBitmap(cached);else thumbnails.execute(()->{if(destroyed||generation!=stripGeneration)return;Bitmap result=decodeImage(photo.uri,160);handler.post(()->{if(destroyed||generation!=stripGeneration)return;if(result!=null){thumbCache.put(photo.uri,result);image.setImageBitmap(result);}});});}showSelection(gallery.follow);}
 void movePhoto(int offset){gallery.move(offset);showSelection(true);}void showSelection(boolean scroll){int index=gallery.index();boolean any=index>=0;previousPhoto.setEnabled(index>0);nextPhoto.setEnabled(any&&index<gallery.photos.size()-1);livePhoto.setEnabled(!gallery.photos.isEmpty());livePhoto.setText(gallery.follow?"● Acompanhando":"Acompanhar novas");livePhoto.setTextColor(gallery.follow?BLUE:TEXT);galleryInfo.setText(gallery.photos.isEmpty()?"As miniaturas aparecem quando o processamento termina.":(any?(index+1)+" / "+gallery.photos.size():"Foto")+" · últimas 60 processadas"+(gallery.follow?"":" · prévia fixada"));for(Map.Entry<String,FrameLayout> entry:tiles.entrySet()){boolean chosen=entry.getKey().equals(gallery.selected);String st=photoStates.get(entry.getKey());GradientDrawable bg=border(CARD,12);if(chosen)bg.setStroke(dp(2),BLUE);else if("review".equals(st))bg.setStroke(dp(2),WARNING);entry.getValue().setBackground(bg);}if(!gallery.selected.isEmpty())loadPreview(gallery.selected);if(scroll){FrameLayout tile=tiles.get(gallery.selected);if(tile!=null)filmScroll.post(()->filmScroll.smoothScrollTo(Math.max(0,tile.getLeft()-(filmScroll.getWidth()-tile.getWidth())/2),0));}}
 Bitmap decodeImage(String value,int edge){try{Uri uri=Uri.parse(value);BitmapFactory.Options opts=new BitmapFactory.Options();opts.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,opts);}if(opts.outWidth<=0||opts.outHeight<=0)return null;opts.inJustDecodeBounds=false;opts.inSampleSize=1;while(Math.max(opts.outWidth,opts.outHeight)/opts.inSampleSize>edge)opts.inSampleSize*=2;try(InputStream in=getContentResolver().openInputStream(uri)){return BitmapFactory.decodeStream(in,null,opts);}}catch(Exception e){return null;}}
 void loadPreview(String value){if(value.equals(requestedUri))return;requestedUri=value;final long gen=++previewGeneration;preview.setImageDrawable(null);shownUri="";previewTitle.setText(gallery.name());previewSub.setText("Carregando prévia…");images.execute(()->{if(destroyed||gen!=previewGeneration)return;final Bitmap ready=decodeImage(value,1400);handler.post(()->{if(destroyed||gen!=previewGeneration){if(ready!=null)ready.recycle();return;}empty.setVisibility(View.GONE);if(ready==null){previewSub.setText("Arquivo indisponível · confira a Galeria");return;}if(previewBitmap!=null&&previewBitmap!=ready)previewBitmap.recycle();previewBitmap=ready;preview.setImageBitmap(ready);shownUri=value;previewTitle.setText(gallery.name());updatePreviewStatus();});});}
 void updatePreviewStatus(){if(previewState==null||gallery.selected==null||gallery.selected.isEmpty()){if(previewState!=null)previewState.setText("AGUARDANDO");if(previewScore!=null)previewScore.setText("");return;}String st=photoStates.get(gallery.selected);Integer score=photoScores.get(gallery.selected);if(st==null){try(Cursor c=database.getReadableDatabase().rawQuery("SELECT state,score,error FROM jobs WHERE edited=? LIMIT 1",new String[]{gallery.selected})){if(c.moveToFirst()){st=c.getString(0);score=c.getInt(1);}}}String label="done".equals(st)?"APROVADA":"review".equals(st)?"REVISÃO":"PROCESSANDO";previewState.setText(label);previewState.setBackground(shape("review".equals(st)?0xddff9f43:0xdd20b46a,16));previewScore.setText(score!=null&&score>0?score+"/10":"");previewScore.setVisibility(score!=null&&score>0?View.VISIBLE:View.GONE);previewSub.setText(("review".equals(st)?"Sob revisão · upload bloqueado":"Editada e pronta")+" · toque para ampliar");}
 void fullscreen(){if(!shownUri.isEmpty())openImage(shownUri);}

 class LumoMark extends View{Paint p=new Paint(3);LumoMark(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),r=Math.min(w,h)*.34f;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.min(w,h)*.24f);p.setStrokeCap(Paint.Cap.ROUND);p.setShader(new SweepGradient(w/2f,h/2f,new int[]{0xff22dff3,0xff0072ff,0xff2336d7,0xff22dff3},null));c.drawCircle(w/2f,h/2f,r,p);p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(CARD);c.drawCircle(w*.60f,h*.43f,Math.min(w,h)*.12f,p);}}
 class CameraArt extends View{Paint paint=new Paint(3);CameraArt(Context c){super(c);}protected void onDraw(Canvas canvas){super.onDraw(canvas);float sx=getWidth()/110f,sy=getHeight()/100f;canvas.save();canvas.scale(sx,sy);paint.setStyle(Paint.Style.FILL);paint.setColor(0xff1f2937);canvas.drawCircle(55,50,47,paint);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(2);paint.setColor(CYAN);canvas.drawRoundRect(24,34,86,73,8,8,paint);canvas.drawCircle(55,54,13,paint);canvas.drawCircle(55,54,7,paint);canvas.drawLine(36,33,41,25,paint);canvas.drawLine(41,25,64,25,paint);canvas.drawLine(64,25,70,33,paint);canvas.restore();}}
 void chooseTransport(){new AlertDialog.Builder(this).setTitle("Como conectar?").setItems(new String[]{"Cabo USB","Wi‑Fi · experimental"},(d,n)->{if(n==0)choose();else wifiDialog();}).show();}
 void wifiDialog(){android.net.ConnectivityManager cm=getSystemService(android.net.ConnectivityManager.class);android.net.Network found=null;String gateway="192.168.0.1";for(android.net.Network n:cm.getAllNetworks()){android.net.NetworkCapabilities caps=cm.getNetworkCapabilities(n);if(caps!=null&&caps.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI)){found=n;android.net.LinkProperties props=cm.getLinkProperties(n);if(props!=null)for(android.net.RouteInfo route:props.getRoutes())if(route.isDefaultRoute()&&route.getGateway() instanceof java.net.Inet4Address)gateway=route.getGateway().getHostAddress();break;}}final android.net.Network wifi=found;LinearLayout box=vertical();box.setPadding(dp(22),dp(8),dp(22),dp(8));label(box,"Na SL2: Wi‑Fi → Controle remoto (EOS Utility) → Registrar dispositivo. Conecte o celular à rede da câmera.",13);EditText ip=new EditText(this);ip.setText(getSharedPreferences("hisho",0).getString("wifiHost",gateway));ip.setTextColor(TEXT);ip.setHint("IP da câmera");box.addView(ip);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Conectar por Wi‑Fi").setView(box).setPositiveButton("Conectar",null).setNeutralButton("Abrir Wi‑Fi",(d,n)->startActivity(new Intent(android.provider.Settings.ACTION_WIFI_SETTINGS))).setNegativeButton("Cancelar",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String host=ip.getText().toString().trim();if(!validIp(host)){ip.setError("Informe um IPv4 válido.");return;}if(wifi==null){message("Conecte ao Wi‑Fi da câmera e tente novamente.");return;}getSharedPreferences("hisho",0).edit().putString("wifiHost",host).apply();dialog.dismiss();startCamera(null,host,wifi);}));dialog.show();}
 static boolean validIp(String host){String[] parts=host.split("\\.",-1);if(parts.length!=4)return false;for(String part:parts){if(!part.matches("[0-9]{1,3}"))return false;int v=Integer.parseInt(part);if(v>255)return false;}return true;}void choose(){UsbManager m=(UsbManager)getSystemService(USB_SERVICE);ArrayList<UsbDevice> ds=new ArrayList<>();for(UsbDevice d:m.getDeviceList().values())if(d.getVendorId()==0x04a9)ds.add(d);if(ds.isEmpty()){message("Nenhuma Canon encontrada. Conecte um cabo de dados USB/OTG.");return;}if(ds.size()==1){permission(ds.get(0));return;}String[] names=new String[ds.size()];for(int i=0;i<ds.size();i++)names[i]=ds.get(i).getProductName();new AlertDialog.Builder(this).setTitle("Escolha a câmera").setItems(names,(d,n)->permission(ds.get(n))).show();}void permission(UsbDevice d){UsbManager m=(UsbManager)getSystemService(USB_SERVICE);if(m.hasPermission(d)){start(d);return;}Intent i=new Intent(USB).setPackage(getPackageName());PendingIntent pi=PendingIntent.getBroadcast(this,1,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_MUTABLE);m.requestPermission(d,pi);}void start(UsbDevice d){startCamera(d,null,null);}
 void startCamera(UsbDevice d,String wifiHost,android.net.Network wifiNetwork){if(CaptureService.active!=null){message("Serviço já ativo.");return;}try{android.content.SharedPreferences p=getSharedPreferences("hisho",0);JSONObject cfg=new JSONObject();cfg.put("auto",auto==null?p.getBoolean("autoEnabled",true):auto.isChecked());cfg.put("edge",resolution==null?2560:resolution.getSelectedItemPosition()==0?2560:resolution.getSelectedItemPosition()==1?1920:0);cfg.put("curation",curation==null?p.getBoolean("curationEnabled",true):curation.isChecked());cfg.put("curationSensitivity",curationSensitivity==null?p.getInt("curationSensitivity",1):curationSensitivity.getSelectedItemPosition());cfg.put("backfill",backfill==null?p.getBoolean("backfillEnabled",true):backfill.isChecked());if((preset==null?p.getBoolean("presetEnabled",true):preset.isChecked())&&presetData!=null)cfg.put("preset",presetData);Intent i=new Intent(this,CaptureService.class).putExtra("settings",cfg.toString());if(d!=null)i.putExtra("device",d);if(wifiHost!=null)i.putExtra("wifiHost",wifiHost).putExtra("wifiNetwork",wifiNetwork);startForegroundService(i);}catch(Exception e){message(e.getMessage());}}
 static String read(InputStream stream)throws IOException{try(InputStream s=stream;ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] a=new byte[8192];int n;while((n=s.read(a))!=-1){if(b.size()+n>1024*1024)throw new IOException("Arquivo maior que 1 MB.");b.write(a,0,n);}return b.toString("UTF-8");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==30){if(result==RESULT_OK){getSharedPreferences("hisho",0).edit().putString("fottoLastStatus","Conta conectada. Carregando eventos…").apply();loadFottoGalleries();updateFottoStatus();}return;}if(request==20&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);try{getContentResolver().takePersistableUriPermission(uri,flags);getSharedPreferences("hisho",0).edit().putString("exportTreeUri",uri.toString()).apply();updateExportFolder();updateFottoStatus();message("Pasta de exportação salva.");}catch(Exception e){message("Não foi possível manter acesso à pasta: "+e.getMessage());}return;}if(request==10&&result==RESULT_OK&&data!=null)try{JSONObject parsed=PhotoEditor.parse(read(getContentResolver().openInputStream(data.getData())));presetData=parsed;presetName="Preset importado";try(Cursor c=getContentResolver().query(data.getData(),new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())presetName=c.getString(0).replaceFirst("(?i)\\.xmp$","");}getSharedPreferences("hisho",0).edit().putString("preset",parsed.toString()).putString("presetName",presetName).apply();presetLabel.setText(presetName);message("Preset importado.");}catch(Exception e){message("Preset anterior mantido: "+e.getMessage());}}
 void message(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 protected void onResume(){super.onResume();gallerySignature="";galleryListSignature="";deliverySignature="";requestedUri="";thumbCache.evictAll();handler.removeCallbacks(update);handler.post(update);}protected void onPause(){handler.removeCallbacks(update);super.onPause();}protected void onSaveInstanceState(Bundle state){state.putInt("page",selected);state.putBoolean("follow",gallery.follow);state.putString("photo",gallery.selected);super.onSaveInstanceState(state);}protected void onDestroy(){destroyed=true;previewGeneration++;stripGeneration++;thumbnails.shutdownNow();thumbCache.evictAll();handler.removeCallbacks(update);images.shutdownNow();fottoNetwork.shutdownNow();if(preview!=null)preview.setImageDrawable(null);if(previewBitmap!=null)previewBitmap.recycle();database.close();if(registered)unregisterReceiver(receiver);super.onDestroy();}
}
