package com.hisho.tether;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

/** Manual editor that layers refinements over the automatic/preset render. */
public class ManualEditorActivity extends Activity{
 static final int BG=0xfff7f9fc,CARD=0xffffffff,LINE=0xffe5eaf0,TEXT=0xff0b1220,MUTED=0xff6f7d91,BLUE=0xff0b7cff,CYAN=0xff22dff3,ORANGE=0xffff9f43;
 final Handler handler=new Handler();final ExecutorService worker=Executors.newSingleThreadExecutor();final LinkedHashMap<String,SeekBar> bars=new LinkedHashMap<>();final LinkedHashMap<String,TextView> values=new LinkedHashMap<>();
 Jobs jobs;ImageView preview;TextView title,status;Bitmap baseBitmap,previewBitmap;String focusId="";ArrayList<String> targets=new ArrayList<>();JSONObject manual=new JSONObject();volatile long previewGen=0;boolean destroyed=false;
 final String[] keys={"exposure","contrast","highlights","shadows","whites","blacks","temperature","tint","vibrance","saturation"};
 final String[] names={"Exposição","Contraste","Realces","Sombras","Brancos","Pretos","Temperatura","Matiz","Vibração","Saturação"};

 int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}GradientDrawable shape(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}GradientDrawable border(int c,int r){GradientDrawable d=shape(c,r);d.setStroke(dp(1),LINE);return d;}
 TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create(bold?"sans-serif-medium":"sans-serif",0));return t;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void gap(LinearLayout p,int h){p.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 Button button(LinearLayout p,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(TEXT);b.setBackground(border(0xfffbfcfe,14));b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.topMargin=dp(8);p.addView(b,lp);return b;}
 void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(shape(BLUE,14));}

 @Override public void onCreate(Bundle state){super.onCreate(state);jobs=new Jobs(this);focusId=getIntent().getStringExtra("focusId");String packed=getIntent().getStringExtra("jobIds");if(packed!=null)for(String id:packed.split(","))if(!id.trim().isEmpty()&&!targets.contains(id.trim()))targets.add(id.trim());if(focusId==null)focusId="";if(!focusId.isEmpty()&&!targets.contains(focusId))targets.add(0,focusId);if(focusId.isEmpty()&&!targets.isEmpty())focusId=targets.get(0);
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(CARD);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=vertical();root.setPadding(dp(18),dp(14),dp(18),dp(26));root.setBackgroundColor(BG);scroll.addView(root);setContentView(scroll);
  LinearLayout top=row();TextView brand=text("LUMO · EDITOR",17,TEXT,true);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button close=new Button(this);close.setText("Fechar");close.setAllCaps(false);close.setOnClickListener(v->finish());top.addView(close,new LinearLayout.LayoutParams(dp(90),dp(46)));root.addView(top);gap(root,12);
  title=text("Editor manual",25,TEXT,true);root.addView(title);gap(root,4);TextView sub=text("Refine a edição automática sem alterar o JPEG original.",13,MUTED,false);root.addView(sub);gap(root,14);
  preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackground(border(CARD,18));root.addView(preview,new LinearLayout.LayoutParams(-1,dp(420)));gap(root,10);status=text("Preparando prévia…",12,MUTED,false);root.addView(status);gap(root,18);
  LinearLayout controls=vertical();controls.setPadding(dp(16),dp(14),dp(16),dp(14));controls.setBackground(border(CARD,18));root.addView(controls);
  for(int i=0;i<keys.length;i++)addSlider(controls,keys[i],names[i],"exposure".equals(keys[i])?-200:-100,"exposure".equals(keys[i])?200:100);
  gap(root,14);LinearLayout clip=row();Button copy=new Button(this);copy.setText("Copiar ajustes");copy.setAllCaps(false);copy.setOnClickListener(v->copyAdjustments());clip.addView(copy,new LinearLayout.LayoutParams(0,dp(50),1));Button paste=new Button(this);paste.setText("Colar ajustes");paste.setAllCaps(false);paste.setOnClickListener(v->pasteAdjustments());clip.addView(paste,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(clip);
  Button reset=button(root,"Zerar ajustes manuais",v->{setManual(new JSONObject());schedulePreview();});
  Button current=button(root,"Salvar nesta foto",v->saveTargets(Collections.singletonList(focusId)));primary(current);
  Button batch=button(root,targets.size()>1?"Aplicar em "+targets.size()+" fotos selecionadas":"Selecione várias fotos na Galeria para edição em lote",v->{if(targets.size()>1)saveTargets(new ArrayList<>(targets));else toast("Selecione várias fotos na Galeria primeiro.");});if(targets.size()>1)primary(batch);else batch.setEnabled(false);
  gap(root,10);TextView note=text("Copiar/Colar guarda apenas os ajustes manuais. Cada foto mantém sua correção automática e seu preset de origem. Ao salvar, o LUMO reprocessa a partir do original para evitar perda acumulada de qualidade.",12,MUTED,false);root.addView(note);
  loadFocus();
 }

 void addSlider(LinearLayout parent,String key,String label,int min,int max){LinearLayout head=row();TextView name=text(label,14,TEXT,true);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView value=text(format(key,0),13,BLUE,true);head.addView(value);parent.addView(head);SeekBar bar=new SeekBar(this);bar.setMax(max-min);bar.setProgress(-min);bar.setProgressTintList(ColorStateList.valueOf(BLUE));bar.setThumbTintList(ColorStateList.valueOf(BLUE));bar.setTag(new int[]{min,max});bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean user){int[] range=(int[])b.getTag();int v=p+range[0];try{manual.put(key,"exposure".equals(key)?v/100.0:v);}catch(Exception ignored){}value.setText(format(key,v));if(user)schedulePreview();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});parent.addView(bar,new LinearLayout.LayoutParams(-1,dp(42)));bars.put(key,bar);values.put(key,value);}
 String format(String key,int v){if("exposure".equals(key))return String.format(Locale.getDefault(),"%+.2f EV",v/100.0);return (v>0?"+":"")+v;}
 int intValue(String key,JSONObject obj){if("exposure".equals(key))return (int)Math.round(obj.optDouble(key,0)*100);return obj.optInt(key,0);}
 void setManual(JSONObject obj){manual=new JSONObject();for(String key:keys){int v=intValue(key,obj);try{manual.put(key,"exposure".equals(key)?v/100.0:v);}catch(Exception ignored){}SeekBar b=bars.get(key);int[] range=(int[])b.getTag();v=Math.max(range[0],Math.min(range[1],v));b.setProgress(v-range[0]);TextView val=values.get(key);if(val!=null)val.setText(format(key,v));}}

 void loadFocus(){if(focusId.isEmpty()){status.setText("Nenhuma foto selecionada.");return;}worker.execute(()->{File original=null,base=null;try{String[] j=jobs.editorJob(focusId);if(j==null)throw new IOException("Foto não encontrada no histórico.");String name=j[1],settingsText=j[2],originalUri=j[3];JSONObject settings=new JSONObject(settingsText);JSONObject existing=settings.optJSONObject("manual");handler.post(()->{title.setText(name.replaceFirst("(?i)\\.jpg$","")+" · "+targets.size()+" selecionada(s)");setManual(existing==null?new JSONObject():existing);});original=new File(getCacheDir(),"editor_original_"+System.nanoTime()+".jpg");base=new File(getCacheDir(),"editor_base_"+System.nanoTime()+".jpg");copyUri(originalUri,original);settings.remove("manual");settings.put("edge",1400);PhotoEditor.edit(original,base,settings);Bitmap ready=BitmapFactory.decodeFile(base.toString());if(ready==null)throw new IOException("Não foi possível gerar a prévia.");final Bitmap done=ready;handler.post(()->{if(destroyed){done.recycle();return;}if(baseBitmap!=null)baseBitmap.recycle();baseBitmap=done;status.setText("Prévia pronta · ajustes sobre Auto + Preset");schedulePreview();});}catch(Exception e){String msg=e.getMessage();handler.post(()->status.setText("Falha ao preparar editor · "+msg));}finally{if(original!=null)original.delete();if(base!=null)base.delete();}});}
 void schedulePreview(){final long gen=++previewGen;handler.postDelayed(()->{if(destroyed||gen!=previewGen||baseBitmap==null)return;JSONObject snapshot=copyJson(manual);worker.execute(()->{Bitmap out=null;try{out=baseBitmap.copy(Bitmap.Config.ARGB_8888,true);if(out==null)return;PhotoEditor.manualBitmap(out,snapshot);final Bitmap ready=out;handler.post(()->{if(destroyed||gen!=previewGen){ready.recycle();return;}if(previewBitmap!=null&&previewBitmap!=baseBitmap)previewBitmap.recycle();previewBitmap=ready;preview.setImageBitmap(ready);});}catch(Exception e){if(out!=null)out.recycle();}});},110);}
 JSONObject copyJson(JSONObject src){try{return new JSONObject(src.toString());}catch(Exception e){return new JSONObject();}}
 void copyAdjustments(){getSharedPreferences("hisho",0).edit().putString("manualEditClipboard",manual.toString()).apply();toast("Ajustes copiados.");}
 void pasteAdjustments(){String raw=getSharedPreferences("hisho",0).getString("manualEditClipboard","");if(raw.isEmpty()){toast("Nenhum ajuste copiado ainda.");return;}try{setManual(new JSONObject(raw));schedulePreview();toast("Ajustes colados.");}catch(Exception e){toast("Não foi possível colar os ajustes.");}}

 void saveTargets(List<String> ids){if(ids==null||ids.isEmpty()||ids.get(0).isEmpty())return;final JSONObject chosen=copyJson(manual);setControls(false);status.setText("Aplicando em "+ids.size()+" foto(s)…");worker.execute(()->{int ok=0,review=0,fail=0,sentBefore=0;String lastError="";for(String id:ids){try{SaveResult r=saveOne(id,chosen);ok++;if(r.review)review++;if(r.wasSent)sentBefore++;}catch(Exception e){fail++;lastError=e.getMessage();}}final int fOk=ok,fReview=review,fFail=fail,fSent=sentBefore;final String fErr=lastError;handler.post(()->{setControls(true);String msg="Concluído · "+fOk+" salva(s)"+(fReview>0?" · "+fReview+" sob revisão":"")+(fFail>0?" · "+fFail+" falha(s)":"");if(fSent>0)msg+=" · "+fSent+" já tinha(m) sido enviada(s) ao Fotto";status.setText(msg+(fErr.isEmpty()?"":"\nÚltimo erro: "+fErr));toast(msg);});});}
 static final class SaveResult{boolean review,wasSent;SaveResult(boolean r,boolean s){review=r;wasSent=s;}}
 SaveResult saveOne(String id,JSONObject chosen)throws Exception{String[] j=jobs.editorJob(id);if(j==null)throw new IOException("Foto "+id+" não encontrada.");String name=j[1],settingsText=j[2],originalUri=j[3],editedUri=j[4],state=j[5];JSONObject settings=new JSONObject(settingsText);settings.put("manual",copyJson(chosen));File original=new File(getCacheDir(),"manual_original_"+id+".jpg"),output=new File(getCacheDir(),"manual_output_"+id+".jpg");try{copyUri(originalUri,original);PhotoEditor.edit(original,output,settings);boolean curate=settings.optBoolean("curation",true);Curator.Result quality=curate?Curator.analyze(output,settings.optInt("curationSensitivity",1)):null;boolean review=quality!=null&&quality.review;boolean wasSent=jobs.fottoWasSent(id);jobs.updateSettings(id,settings.toString());jobs.fottoDiscardUnsent(id);
   if(review){String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Sob Revisao",name.replaceFirst("(?i)\\.jpg$","_REVISAO.jpg"),id,"edited");jobs.set(id,"review","error",quality.reason);if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}return new SaveResult(true,wasSent);}
   if("done".equals(state)&&editedUri!=null&&!editedUri.isEmpty())jobs.overwrite(output,editedUri);else{String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Editadas",name.replaceFirst("(?i)\\.jpg$","_Editada.jpg"),id,"edited");if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}}
   jobs.set(id,"done","error",null);if(!wasSent)FottoSync.kick(this);return new SaveResult(false,wasSent);
  }finally{original.delete();output.delete();}}
 void copyUri(String raw,File out)throws IOException{if(raw==null||raw.isEmpty())throw new IOException("Original não encontrado. O editor precisa do arquivo original preservado.");try(InputStream in=getContentResolver().openInputStream(Uri.parse(raw));OutputStream dst=new FileOutputStream(out)){if(in==null)throw new IOException("Original indisponível.");Jobs.copy(in,dst);}}
 void setControls(boolean enabled){for(SeekBar b:bars.values())b.setEnabled(enabled);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){destroyed=true;previewGen++;worker.shutdownNow();if(baseBitmap!=null)baseBitmap.recycle();if(previewBitmap!=null&&previewBitmap!=baseBitmap)previewBitmap.recycle();jobs.close();super.onDestroy();}
}
