package com.hisho.tether;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

/** Editor manual: base Auto + Preset, preview contínua e sincronização seletiva em lote. */
public class ManualEditorActivity extends Activity{
 static final int BG=0xfff7f9fc,CARD=0xffffffff,LINE=0xffe5eaf0,TEXT=0xff0b1220,MUTED=0xff6f7d91,BLUE=0xff0b7cff,GREEN=0xff27b879,ORANGE=0xffff9f43;
 final Handler handler=new Handler();final ExecutorService worker=Executors.newSingleThreadExecutor();final ExecutorService thumbs=Executors.newSingleThreadExecutor();final LinkedHashMap<String,SeekBar> bars=new LinkedHashMap<>();final LinkedHashMap<String,TextView> values=new LinkedHashMap<>();final LinkedHashMap<String,TextView> bases=new LinkedHashMap<>();
 Jobs jobs;ImageView preview;TextView title,status,baseStatus;Bitmap originalBitmap,baseBitmap,previewBitmap;String focusId="";ArrayList<String> targets=new ArrayList<>();JSONObject baseValues=new JSONObject(),autoValues=new JSONObject(),presetValues=new JSONObject(),currentValues=new JSONObject(),sourcePreset=new JSONObject();boolean settingControls=false,destroyed=false,showingBefore=false;volatile boolean previewBusy=false,previewQueued=false;LinearLayout targetStrip;Button beforeAfter,syncButton;
 final String[] keys={"exposure","contrast","highlights","shadows","whites","blacks","temperature","tint","vibrance","saturation"};
 final String[] names={"Exposição","Contraste","Realces","Sombras","Brancos","Pretos","Temperatura","Matiz","Vibração","Saturação"};

 int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}GradientDrawable shape(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}GradientDrawable border(int c,int r){GradientDrawable d=shape(c,r);d.setStroke(dp(1),LINE);return d;}
 TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create(bold?"sans-serif-medium":"sans-serif",0));return t;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void gap(LinearLayout p,int h){p.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 Button button(LinearLayout p,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(TEXT);b.setBackground(border(0xfffbfcfe,14));b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.topMargin=dp(8);p.addView(b,lp);return b;}
 void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(shape(BLUE,14));}

 @Override public void onCreate(Bundle state){super.onCreate(state);jobs=new Jobs(this);focusId=getIntent().getStringExtra("focusId");String packed=getIntent().getStringExtra("jobIds");if(packed!=null)for(String id:packed.split(","))if(!id.trim().isEmpty()&&!targets.contains(id.trim()))targets.add(id.trim());if(focusId==null)focusId="";if(!focusId.isEmpty()&&!targets.contains(focusId))targets.add(0,focusId);if(focusId.isEmpty()&&!targets.isEmpty())focusId=targets.get(0);
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(CARD);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=vertical();root.setPadding(dp(16),dp(12),dp(16),dp(24));root.setBackgroundColor(BG);scroll.addView(root);setContentView(scroll);
  LinearLayout top=row();TextView brand=text("LUMO · EDITAR",17,TEXT,true);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button close=new Button(this);close.setText("Fechar");close.setAllCaps(false);close.setOnClickListener(v->finish());top.addView(close,new LinearLayout.LayoutParams(dp(88),dp(44)));root.addView(top);gap(root,8);
  title=text("Editor",23,TEXT,true);root.addView(title);gap(root,3);baseStatus=text("Auto + Preset aplicado · refinamento não destrutivo",12,MUTED,false);root.addView(baseStatus);gap(root,10);
  FrameLayout photo=new FrameLayout(this);photo.setBackground(border(CARD,18));root.addView(photo,new LinearLayout.LayoutParams(-1,dp(430)));preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);photo.addView(preview,new FrameLayout.LayoutParams(-1,-1));TextView hint=text("TOQUE E SEGURE: antes",10,Color.WHITE,true);hint.setPadding(dp(10),dp(7),dp(10),dp(7));hint.setBackground(shape(0xaa0b1220,16));FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.RIGHT);hp.setMargins(0,dp(10),dp(10),0);photo.addView(hint,hp);preview.setOnLongClickListener(v->{showBefore(true);return true;});preview.setOnTouchListener((v,e)->{if(e.getAction()==android.view.MotionEvent.ACTION_UP||e.getAction()==android.view.MotionEvent.ACTION_CANCEL)showBefore(false);return false;});
  gap(root,8);status=text("Preparando Auto + Preset…",12,MUTED,false);root.addView(status);gap(root,10);

  HorizontalScrollView filmScroll=new HorizontalScrollView(this);filmScroll.setHorizontalScrollBarEnabled(false);targetStrip=row();filmScroll.addView(targetStrip);root.addView(filmScroll,new LinearLayout.LayoutParams(-1,dp(78)));buildTargetStrip();

  gap(root,10);LinearLayout actions=row();beforeAfter=smallAction("Antes / Depois",v->{showingBefore=!showingBefore;showBefore(showingBefore);});actions.addView(beforeAfter,new LinearLayout.LayoutParams(0,dp(48),1));Button copy=smallAction("Copiar edição",v->copyAdjustments());actions.addView(copy,new LinearLayout.LayoutParams(0,dp(48),1));syncButton=smallAction(targets.size()>1?"Sincronizar "+targets.size():"Sincronizar",v->syncDialog());syncButton.setEnabled(targets.size()>1);actions.addView(syncButton,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(actions);

  gap(root,12);root.addView(text("AJUSTES",11,BLUE,true));gap(root,6);HorizontalScrollView controlScroll=new HorizontalScrollView(this);controlScroll.setHorizontalScrollBarEnabled(false);LinearLayout controlRail=row();controlScroll.addView(controlRail);root.addView(controlScroll,new LinearLayout.LayoutParams(-1,dp(168)));for(int i=0;i<keys.length;i++)addSliderCard(controlRail,keys[i],names[i]);

  gap(root,10);Button current=button(root,"Salvar nesta foto",v->saveTargetsSelective(Collections.singletonList(focusId),new LinkedHashSet<>(Arrays.asList(keys)),false));primary(current);
  Button batch=button(root,targets.size()>1?"Aplicar todos os refinamentos em "+targets.size()+" fotos":"Selecione várias fotos na Galeria para edição em lote",v->{if(targets.size()>1)saveTargetsSelective(new ArrayList<>(targets),new LinkedHashSet<>(Arrays.asList(keys)),false);else toast("Selecione várias fotos na Galeria primeiro.");});if(targets.size()>1)primary(batch);else batch.setEnabled(false);
  button(root,"Voltar ao Auto + Preset",v->{setCurrentFromDelta(new JSONObject());requestPreview();});
  gap(root,8);root.addView(text("Cada foto mantém o próprio Auto. Ao sincronizar, você escolhe exatamente o que deseja copiar: exposição, contraste, luz, cor, preset ou tudo.",12,MUTED,false));
  loadFocus();
 }

 Button smallAction(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(11);b.setTextColor(TEXT);b.setBackground(border(CARD,12));b.setOnClickListener(l);return b;}

 void buildTargetStrip(){targetStrip.removeAllViews();for(String id:targets){FrameLayout tile=new FrameLayout(this);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(70),dp(70));lp.rightMargin=dp(7);targetStrip.addView(tile,lp);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(border(CARD,10));tile.addView(image,new FrameLayout.LayoutParams(-1,-1));TextView check=text(id.equals(focusId)?"●":"",10,Color.WHITE,true);check.setGravity(Gravity.CENTER);check.setBackground(shape(0xaa0b7cff,12));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(dp(22),dp(22),Gravity.TOP|Gravity.RIGHT);tile.addView(check,cp);tile.setOnClickListener(v->{if(!id.equals(focusId)){focusId=id;showingBefore=false;buildTargetStrip();loadFocus();}});thumbs.execute(()->{String[] j=jobs.editorJob(id);if(j==null)return;String raw=(j[4]!=null&&!j[4].isEmpty())?j[4]:j[3];final Bitmap b=decodeUri(raw,160);handler.post(()->{if(!destroyed&&b!=null)image.setImageBitmap(b);});});}}

 Bitmap decodeUri(String raw,int edge){if(raw==null||raw.isEmpty())return null;try{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(Uri.parse(raw))){BitmapFactory.decodeStream(in,null,o);}if(o.outWidth<=0)return null;o.inJustDecodeBounds=false;o.inSampleSize=1;while(Math.max(o.outWidth,o.outHeight)/o.inSampleSize>edge)o.inSampleSize*=2;try(InputStream in=getContentResolver().openInputStream(Uri.parse(raw))){return BitmapFactory.decodeStream(in,null,o);}}catch(Exception e){return null;}}

 void addSliderCard(LinearLayout rail,String key,String label){LinearLayout card=vertical();card.setPadding(dp(12),dp(10),dp(12),dp(10));card.setBackground(border(CARD,15));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(235),dp(158));lp.rightMargin=dp(9);rail.addView(card,lp);LinearLayout head=row();TextView name=text(label,13,TEXT,true);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView value=text(format(key,0),12,BLUE,true);head.addView(value);card.addView(head);gap(card,3);TextView base=text("Base · aguardando…",10,MUTED,false);base.setMaxLines(2);card.addView(base);SeekBar bar=new SeekBar(this);boolean ev="exposure".equals(key);int min=ev?-500:-1000,max=ev?500:1000;bar.setMax(max-min);bar.setProgress(-min);bar.setProgressTintList(ColorStateList.valueOf(BLUE));bar.setThumbTintList(ColorStateList.valueOf(BLUE));bar.setTag(new int[]{min,max});bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean user){int[] range=(int[])b.getTag();double v=sliderValue(key,p+range[0]);try{currentValues.put(key,v);}catch(Exception ignored){}value.setText(format(key,v));if(user&&!settingControls){showingBefore=false;requestPreview();}}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});card.addView(bar,new LinearLayout.LayoutParams(-1,dp(50)));bars.put(key,bar);values.put(key,value);bases.put(key,base);}
 double sliderValue(String key,int raw){return "exposure".equals(key)?raw/100.0:raw/10.0;}int sliderRaw(String key,double v){return (int)Math.round(v*("exposure".equals(key)?100:10));}
 String format(String key,double v){if("exposure".equals(key))return String.format(Locale.getDefault(),"%+.2f EV",v);return String.format(Locale.getDefault(),"%+.1f",v);}double val(JSONObject o,String key){return o==null?0:o.optDouble(key,0);}JSONObject copyJson(JSONObject src){try{return new JSONObject(src==null?"{}":src.toString());}catch(Exception e){return new JSONObject();}}
 JSONObject deltaFromCurrent(){JSONObject d=new JSONObject();for(String key:keys)try{d.put(key,val(currentValues,key)-val(baseValues,key));}catch(Exception ignored){}return d;}
 void setCurrentFromDelta(JSONObject delta){settingControls=true;currentValues=new JSONObject();for(String key:keys){double v=val(baseValues,key)+val(delta,key);double lo="exposure".equals(key)?-5:-100,hi="exposure".equals(key)?5:100;v=Math.max(lo,Math.min(hi,v));try{currentValues.put(key,v);}catch(Exception ignored){}SeekBar b=bars.get(key);int[] range=(int[])b.getTag();int raw=Math.max(range[0],Math.min(range[1],sliderRaw(key,v)));b.setProgress(raw-range[0]);TextView out=values.get(key);if(out!=null)out.setText(format(key,v));TextView base=bases.get(key);if(base!=null)base.setText(baseText(key));}settingControls=false;}
 String baseText(String key){double a=val(autoValues,key),p=val(presetValues,key),sum=val(baseValues,key);return "Base "+format(key,sum)+" · Auto "+format(key,a)+" · Preset "+format(key,p);}

 void loadFocus(){if(focusId.isEmpty()){status.setText("Nenhuma foto selecionada.");return;}status.setText("Carregando base Auto + Preset…");worker.execute(()->{File original=null,base=null;Bitmap originalReady=null;try{String[] j=jobs.editorJob(focusId);if(j==null)throw new IOException("Foto não encontrada no histórico.");String name=j[1],settingsText=j[2],originalUri=j[3];JSONObject settings=new JSONObject(settingsText);JSONObject existing=settings.optJSONObject("manual");sourcePreset=copyJson(settings.optJSONObject("preset"));original=new File(getCacheDir(),"editor_original_"+System.nanoTime()+".jpg");base=new File(getCacheDir(),"editor_base_"+System.nanoTime()+".jpg");copyUri(originalUri,original);autoValues=settings.optBoolean("auto",true)?PhotoEditor.autoControls(original):new JSONObject();presetValues=PhotoEditor.presetControls(sourcePreset);baseValues=PhotoEditor.sumControls(autoValues,presetValues);JSONObject oldDelta=existing==null?new JSONObject():copyJson(existing);settings.remove("manual");settings.put("edge",960);PhotoEditor.edit(original,base,settings);Bitmap ready=BitmapFactory.decodeFile(base.toString());Bitmap orig=BitmapFactory.decodeFile(original.toString());if(ready==null)throw new IOException("Não foi possível gerar a prévia.");if(orig!=null&&Math.max(orig.getWidth(),orig.getHeight())>1400){double scale=1400.0/Math.max(orig.getWidth(),orig.getHeight());Bitmap scaled=Bitmap.createScaledBitmap(orig,(int)(orig.getWidth()*scale),(int)(orig.getHeight()*scale),true);orig.recycle();orig=scaled;}final Bitmap done=ready,originalDone=orig;handler.post(()->{if(destroyed){done.recycle();if(originalDone!=null)originalDone.recycle();return;}int q=jobs.score(focusId);title.setText(name.replaceFirst("(?i)\\.jpg$","")+(q>0?" · nota "+q+"/10":" · sem nota"));setCurrentFromDelta(oldDelta);recycleBitmaps();baseBitmap=done;originalBitmap=originalDone;baseStatus.setText("Auto + Preset aplicado · "+targets.size()+" selecionada(s)");status.setText("Prévia em tempo real · arraste qualquer controle");buildTargetStrip();requestPreview();});}catch(Exception e){String msg=e.getMessage();if(originalReady!=null)originalReady.recycle();handler.post(()->status.setText("Falha ao preparar editor · "+msg));}finally{if(original!=null)original.delete();if(base!=null)base.delete();}});}

 void recycleBitmaps(){if(originalBitmap!=null){originalBitmap.recycle();originalBitmap=null;}if(previewBitmap!=null&&previewBitmap!=baseBitmap){previewBitmap.recycle();previewBitmap=null;}if(baseBitmap!=null){baseBitmap.recycle();baseBitmap=null;}}
 void showBefore(boolean before){showingBefore=before;if(before&&originalBitmap!=null){preview.setImageBitmap(originalBitmap);beforeAfter.setText("Mostrando original");}else{beforeAfter.setText("Antes / Depois");requestPreview();}}
 void requestPreview(){previewQueued=true;if(showingBefore||destroyed||baseBitmap==null||previewBusy)return;startPreviewFrame();}
 void startPreviewFrame(){if(showingBefore||destroyed||baseBitmap==null||previewBusy)return;previewQueued=false;previewBusy=true;JSONObject delta=deltaFromCurrent();worker.execute(()->{Bitmap out=null;try{out=baseBitmap.copy(Bitmap.Config.ARGB_8888,true);if(out==null)throw new IOException("Sem memória para a prévia.");PhotoEditor.manualBitmap(out,delta);final Bitmap ready=out;handler.post(()->{if(destroyed){ready.recycle();return;}if(previewBitmap!=null&&previewBitmap!=baseBitmap)previewBitmap.recycle();previewBitmap=ready;preview.setImageBitmap(ready);previewBusy=false;if(previewQueued)handler.postDelayed(this::startPreviewFrame,16);});}catch(Exception e){if(out!=null)out.recycle();handler.post(()->{previewBusy=false;if(previewQueued)handler.postDelayed(this::startPreviewFrame,16);});}});}

 void copyAdjustments(){getSharedPreferences("hisho",0).edit().putString("manualEditClipboard",deltaFromCurrent().toString()).apply();toast("Refinamento copiado.");}
 void syncDialog(){if(targets.size()<2){toast("Selecione várias fotos na Galeria.");return;}String[] options={"Exposição","Contraste","Luz · realces/sombras/brancos/pretos","Cor · temperatura/matiz/vibração/saturação","Preset","Tudo"};boolean[] checked={true,true,true,true,false,false};new AlertDialog.Builder(this).setTitle("Sincronizar ajustes").setMessage("O Auto continua individual em cada foto. Escolha somente o que deseja copiar desta foto para as selecionadas.").setMultiChoiceItems(options,checked,(d,which,is)->{checked[which]=is;if(which==5&&is)for(int i=0;i<5;i++)checked[i]=true;}).setPositiveButton("Aplicar",(d,n)->{LinkedHashSet<String> selected=new LinkedHashSet<>();if(checked[0])selected.add("exposure");if(checked[1])selected.add("contrast");if(checked[2])selected.addAll(Arrays.asList("highlights","shadows","whites","blacks"));if(checked[3])selected.addAll(Arrays.asList("temperature","tint","vibrance","saturation"));boolean preset=checked[4]||checked[5];if(selected.isEmpty()&&!preset){toast("Escolha pelo menos um grupo.");return;}saveTargetsSelective(new ArrayList<>(targets),selected,preset);}).setNegativeButton("Cancelar",null).show();}

 void saveTargetsSelective(List<String> ids,Set<String> selectedKeys,boolean includePreset){if(ids==null||ids.isEmpty())return;final JSONObject chosen=deltaFromCurrent();final JSONObject presetCopy=copyJson(sourcePreset);setControls(false);status.setText("Sincronizando em "+ids.size()+" foto(s)…");worker.execute(()->{int ok=0,review=0,fail=0,sentBefore=0;String lastError="";for(String id:ids){try{SaveResult r=saveOne(id,chosen,selectedKeys,includePreset,presetCopy);ok++;if(r.review)review++;if(r.wasSent)sentBefore++;}catch(Exception e){fail++;lastError=e.getMessage();}}final int fOk=ok,fReview=review,fFail=fail,fSent=sentBefore;final String fErr=lastError;handler.post(()->{setControls(true);String msg="Concluído · "+fOk+" salva(s)"+(fReview>0?" · "+fReview+" sob revisão":"")+(fFail>0?" · "+fFail+" falha(s)":"");if(fSent>0)msg+=" · "+fSent+" já enviada(s) ao Fotto";status.setText(msg+(fErr.isEmpty()?"":"\nÚltimo erro: "+fErr));toast(msg);});});}
 static final class SaveResult{boolean review,wasSent;SaveResult(boolean r,boolean s){review=r;wasSent=s;}}
 SaveResult saveOne(String id,JSONObject chosen,Set<String> selectedKeys,boolean includePreset,JSONObject presetCopy)throws Exception{String[] j=jobs.editorJob(id);if(j==null)throw new IOException("Foto "+id+" não encontrada.");String name=j[1],settingsText=j[2],originalUri=j[3],editedUri=j[4],state=j[5];JSONObject settings=new JSONObject(settingsText);JSONObject existing=settings.optJSONObject("manual");JSONObject merged=existing==null?new JSONObject():copyJson(existing);for(String key:selectedKeys)merged.put(key,chosen.optDouble(key,0));settings.put("manual",merged);if(includePreset){if(presetCopy.length()>0)settings.put("preset",copyJson(presetCopy));else settings.remove("preset");}File original=new File(getCacheDir(),"manual_original_"+id+".jpg"),output=new File(getCacheDir(),"manual_output_"+id+".jpg");try{copyUri(originalUri,original);PhotoEditor.edit(original,output,settings);boolean curate=settings.optBoolean("curation",true);Curator.Result quality=curate?Curator.analyze(output,settings.optInt("curationSensitivity",1)):null;boolean review=quality!=null&&quality.review;boolean wasSent=jobs.fottoWasSent(id);if(quality!=null)jobs.setScore(id,quality.score);jobs.updateSettings(id,settings.toString());jobs.fottoDiscardUnsent(id);
   if(review){String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Sob Revisao",name.replaceFirst("(?i)\\.jpg$","_REVISAO.jpg"),id,"edited");jobs.set(id,"review","error",quality.reason);if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}return new SaveResult(true,wasSent);}
   if("done".equals(state)&&editedUri!=null&&!editedUri.isEmpty())jobs.overwrite(output,editedUri);else{String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Editadas",name.replaceFirst("(?i)\\.jpg$","_Editada.jpg"),id,"edited");if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}}
   jobs.set(id,"done","error",null);if(!wasSent)FottoSync.kick(this);return new SaveResult(false,wasSent);
  }finally{original.delete();output.delete();}}
 void copyUri(String raw,File out)throws IOException{if(raw==null||raw.isEmpty())throw new IOException("Original não encontrado. O editor precisa do arquivo original preservado.");try(InputStream in=getContentResolver().openInputStream(Uri.parse(raw));OutputStream dst=new FileOutputStream(out)){if(in==null)throw new IOException("Original indisponível.");Jobs.copy(in,dst);}}
 void setControls(boolean enabled){for(SeekBar b:bars.values())b.setEnabled(enabled);if(syncButton!=null)syncButton.setEnabled(enabled&&targets.size()>1);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){destroyed=true;previewQueued=false;worker.shutdownNow();thumbs.shutdownNow();recycleBitmaps();jobs.close();super.onDestroy();}
}
