package com.hisho.tether;

import android.app.*;import android.os.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

/** Manual editor: sliders show the Auto + Preset baseline and refine it live. */
public class ManualEditorActivity extends Activity{
 static final int BG=0xfff7f9fc,CARD=0xffffffff,LINE=0xffe5eaf0,TEXT=0xff0b1220,MUTED=0xff6f7d91,BLUE=0xff0b7cff,GREEN=0xff27b879;
 final Handler handler=new Handler();final ExecutorService worker=Executors.newSingleThreadExecutor();final LinkedHashMap<String,SeekBar> bars=new LinkedHashMap<>();final LinkedHashMap<String,TextView> values=new LinkedHashMap<>();final LinkedHashMap<String,TextView> bases=new LinkedHashMap<>();
 Jobs jobs;ImageView preview;TextView title,status;Bitmap baseBitmap,previewBitmap;String focusId="";ArrayList<String> targets=new ArrayList<>();JSONObject baseValues=new JSONObject(),autoValues=new JSONObject(),presetValues=new JSONObject(),currentValues=new JSONObject();boolean settingControls=false,destroyed=false;volatile boolean previewBusy=false,previewQueued=false;
 final String[] keys={"exposure","contrast","highlights","shadows","whites","blacks","temperature","tint","vibrance","saturation"};
 final String[] names={"Exposição","Contraste","Realces","Sombras","Brancos","Pretos","Temperatura","Matiz","Vibração","Saturação"};

 int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}GradientDrawable shape(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}GradientDrawable border(int c,int r){GradientDrawable d=shape(c,r);d.setStroke(dp(1),LINE);return d;}
 TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.create(bold?"sans-serif-medium":"sans-serif",0));return t;}
 LinearLayout vertical(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void gap(LinearLayout p,int h){p.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 Button button(LinearLayout p,String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(TEXT);b.setBackground(border(0xfffbfcfe,14));b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.topMargin=dp(8);p.addView(b,lp);return b;}
 void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(shape(BLUE,14));}

 @Override public void onCreate(Bundle state){super.onCreate(state);jobs=new Jobs(this);focusId=getIntent().getStringExtra("focusId");String packed=getIntent().getStringExtra("jobIds");if(packed!=null)for(String id:packed.split(","))if(!id.trim().isEmpty()&&!targets.contains(id.trim()))targets.add(id.trim());if(focusId==null)focusId="";if(!focusId.isEmpty()&&!targets.contains(focusId))targets.add(0,focusId);if(focusId.isEmpty()&&!targets.isEmpty())focusId=targets.get(0);
  getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(CARD);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout root=vertical();root.setPadding(dp(18),dp(14),dp(18),dp(26));root.setBackgroundColor(BG);scroll.addView(root);setContentView(scroll);
  LinearLayout top=row();TextView brand=text("LUMO · EDITOR",17,TEXT,true);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button close=new Button(this);close.setText("Fechar");close.setAllCaps(false);close.setOnClickListener(v->finish());top.addView(close,new LinearLayout.LayoutParams(dp(90),dp(46)));root.addView(top);gap(root,12);
  title=text("Editor",25,TEXT,true);root.addView(title);gap(root,4);root.addView(text("Os controles começam exatamente na base criada por Auto + Preset. Arraste para refinar essa edição.",13,MUTED,false));gap(root,14);
  preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackground(border(CARD,18));root.addView(preview,new LinearLayout.LayoutParams(-1,dp(420)));gap(root,10);status=text("Preparando a base Auto + Preset…",12,MUTED,false);root.addView(status);gap(root,18);
  LinearLayout controls=vertical();controls.setPadding(dp(16),dp(14),dp(16),dp(14));controls.setBackground(border(CARD,18));root.addView(controls);
  for(int i=0;i<keys.length;i++)addSlider(controls,keys[i],names[i]);
  gap(root,14);LinearLayout clip=row();Button copy=new Button(this);copy.setText("Copiar refinamento");copy.setAllCaps(false);copy.setOnClickListener(v->copyAdjustments());clip.addView(copy,new LinearLayout.LayoutParams(0,dp(50),1));Button paste=new Button(this);paste.setText("Colar refinamento");paste.setAllCaps(false);paste.setOnClickListener(v->pasteAdjustments());clip.addView(paste,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(clip);
  button(root,"Voltar ao Auto + Preset",v->{setCurrentFromDelta(new JSONObject());requestPreview();});
  Button current=button(root,"Salvar nesta foto",v->saveTargets(Collections.singletonList(focusId)));primary(current);
  Button batch=button(root,targets.size()>1?"Aplicar refinamento em "+targets.size()+" fotos":"Selecione várias fotos na Galeria para edição em lote",v->{if(targets.size()>1)saveTargets(new ArrayList<>(targets));else toast("Selecione várias fotos na Galeria primeiro.");});if(targets.size()>1)primary(batch);else batch.setEnabled(false);
  gap(root,10);root.addView(text("O número azul é o resultado atual em relação ao original. A linha cinza mostra quanto veio do Auto e quanto veio do Preset. Copiar/Colar copia apenas o refinamento, então cada foto preserva a própria base automática.",12,MUTED,false));
  loadFocus();
 }

 void addSlider(LinearLayout parent,String key,String label){LinearLayout head=row();TextView name=text(label,14,TEXT,true);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView value=text(format(key,0),13,BLUE,true);head.addView(value);parent.addView(head);TextView base=text("Base · aguardando análise…",11,MUTED,false);parent.addView(base);SeekBar bar=new SeekBar(this);boolean ev="exposure".equals(key);int min=ev?-500:-1000,max=ev?500:1000;bar.setMax(max-min);bar.setProgress(-min);bar.setProgressTintList(ColorStateList.valueOf(BLUE));bar.setThumbTintList(ColorStateList.valueOf(BLUE));bar.setTag(new int[]{min,max});bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean user){int[] range=(int[])b.getTag();double v=sliderValue(key,p+range[0]);try{currentValues.put(key,v);}catch(Exception ignored){}value.setText(format(key,v));if(user&&!settingControls)requestPreview();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){if(!settingControls)requestPreview();}});parent.addView(bar,new LinearLayout.LayoutParams(-1,dp(42)));bars.put(key,bar);values.put(key,value);bases.put(key,base);}
 double sliderValue(String key,int raw){return "exposure".equals(key)?raw/100.0:raw/10.0;}
 int sliderRaw(String key,double v){return (int)Math.round(v*("exposure".equals(key)?100:10));}
 String format(String key,double v){if("exposure".equals(key))return String.format(Locale.getDefault(),"%+.2f EV",v);return String.format(Locale.getDefault(),"%+.1f",v);}
 double val(JSONObject o,String key){return o==null?0:o.optDouble(key,0);}
 JSONObject copyJson(JSONObject src){try{return new JSONObject(src==null?"{}":src.toString());}catch(Exception e){return new JSONObject();}}
 JSONObject deltaFromCurrent(){JSONObject d=new JSONObject();for(String key:keys)try{d.put(key,val(currentValues,key)-val(baseValues,key));}catch(Exception ignored){}return d;}
 void setCurrentFromDelta(JSONObject delta){settingControls=true;currentValues=new JSONObject();for(String key:keys){double v=val(baseValues,key)+val(delta,key);double lo="exposure".equals(key)?-5:-100,hi="exposure".equals(key)?5:100;v=Math.max(lo,Math.min(hi,v));try{currentValues.put(key,v);}catch(Exception ignored){}SeekBar b=bars.get(key);int[] range=(int[])b.getTag();int raw=Math.max(range[0],Math.min(range[1],sliderRaw(key,v)));b.setProgress(raw-range[0]);TextView out=values.get(key);if(out!=null)out.setText(format(key,v));TextView base=bases.get(key);if(base!=null)base.setText(baseText(key));}settingControls=false;}
 String baseText(String key){double a=val(autoValues,key),p=val(presetValues,key),sum=val(baseValues,key);return "Base "+format(key,sum)+" · Auto "+format(key,a)+" · Preset "+format(key,p);}

 void loadFocus(){if(focusId.isEmpty()){status.setText("Nenhuma foto selecionada.");return;}worker.execute(()->{File original=null,base=null;try{String[] j=jobs.editorJob(focusId);if(j==null)throw new IOException("Foto não encontrada no histórico.");String name=j[1],settingsText=j[2],originalUri=j[3];JSONObject settings=new JSONObject(settingsText);JSONObject existing=settings.optJSONObject("manual");original=new File(getCacheDir(),"editor_original_"+System.nanoTime()+".jpg");base=new File(getCacheDir(),"editor_base_"+System.nanoTime()+".jpg");copyUri(originalUri,original);autoValues=settings.optBoolean("auto",true)?PhotoEditor.autoControls(original):new JSONObject();presetValues=PhotoEditor.presetControls(settings.optJSONObject("preset"));baseValues=PhotoEditor.sumControls(autoValues,presetValues);JSONObject oldDelta=existing==null?new JSONObject():copyJson(existing);settings.remove("manual");settings.put("edge",960);PhotoEditor.edit(original,base,settings);Bitmap ready=BitmapFactory.decodeFile(base.toString());if(ready==null)throw new IOException("Não foi possível gerar a prévia.");final Bitmap done=ready;handler.post(()->{if(destroyed){done.recycle();return;}title.setText(name.replaceFirst("(?i)\\.jpg$","")+" · "+targets.size()+" selecionada(s)");setCurrentFromDelta(oldDelta);if(baseBitmap!=null)baseBitmap.recycle();baseBitmap=done;status.setText("Prévia ao vivo · base Auto + Preset carregada");requestPreview();});}catch(Exception e){String msg=e.getMessage();handler.post(()->status.setText("Falha ao preparar editor · "+msg));}finally{if(original!=null)original.delete();if(base!=null)base.delete();}});}

 void requestPreview(){previewQueued=true;if(destroyed||baseBitmap==null||previewBusy)return;startPreviewFrame();}
 void startPreviewFrame(){if(destroyed||baseBitmap==null||previewBusy)return;previewQueued=false;previewBusy=true;JSONObject delta=deltaFromCurrent();worker.execute(()->{Bitmap out=null;try{out=baseBitmap.copy(Bitmap.Config.ARGB_8888,true);if(out==null)throw new IOException("Sem memória para a prévia.");PhotoEditor.manualBitmap(out,delta);final Bitmap ready=out;handler.post(()->{if(destroyed){ready.recycle();return;}if(previewBitmap!=null&&previewBitmap!=baseBitmap)previewBitmap.recycle();previewBitmap=ready;preview.setImageBitmap(ready);previewBusy=false;if(previewQueued)handler.postDelayed(this::startPreviewFrame,16);});}catch(Exception e){if(out!=null)out.recycle();handler.post(()->{previewBusy=false;if(previewQueued)handler.postDelayed(this::startPreviewFrame,16);});}});}

 void copyAdjustments(){getSharedPreferences("hisho",0).edit().putString("manualEditClipboard",deltaFromCurrent().toString()).apply();toast("Refinamento copiado.");}
 void pasteAdjustments(){String raw=getSharedPreferences("hisho",0).getString("manualEditClipboard","");if(raw.isEmpty()){toast("Nenhum refinamento copiado ainda.");return;}try{setCurrentFromDelta(new JSONObject(raw));requestPreview();toast("Refinamento colado sobre Auto + Preset.");}catch(Exception e){toast("Não foi possível colar os ajustes.");}}

 void saveTargets(List<String> ids){if(ids==null||ids.isEmpty()||ids.get(0).isEmpty())return;final JSONObject chosen=deltaFromCurrent();setControls(false);status.setText("Aplicando em "+ids.size()+" foto(s)…");worker.execute(()->{int ok=0,review=0,fail=0,sentBefore=0;String lastError="";for(String id:ids){try{SaveResult r=saveOne(id,chosen);ok++;if(r.review)review++;if(r.wasSent)sentBefore++;}catch(Exception e){fail++;lastError=e.getMessage();}}final int fOk=ok,fReview=review,fFail=fail,fSent=sentBefore;final String fErr=lastError;handler.post(()->{setControls(true);String msg="Concluído · "+fOk+" salva(s)"+(fReview>0?" · "+fReview+" sob revisão":"")+(fFail>0?" · "+fFail+" falha(s)":"");if(fSent>0)msg+=" · "+fSent+" já tinha(m) sido enviada(s) ao Fotto";status.setText(msg+(fErr.isEmpty()?"":"\nÚltimo erro: "+fErr));toast(msg);});});}
 static final class SaveResult{boolean review,wasSent;SaveResult(boolean r,boolean s){review=r;wasSent=s;}}
 SaveResult saveOne(String id,JSONObject chosen)throws Exception{String[] j=jobs.editorJob(id);if(j==null)throw new IOException("Foto "+id+" não encontrada.");String name=j[1],settingsText=j[2],originalUri=j[3],editedUri=j[4],state=j[5];JSONObject settings=new JSONObject(settingsText);settings.put("manual",copyJson(chosen));File original=new File(getCacheDir(),"manual_original_"+id+".jpg"),output=new File(getCacheDir(),"manual_output_"+id+".jpg");try{copyUri(originalUri,original);PhotoEditor.edit(original,output,settings);boolean curate=settings.optBoolean("curation",true);Curator.Result quality=curate?Curator.analyze(output,settings.optInt("curationSensitivity",1)):null;boolean review=quality!=null&&quality.review;boolean wasSent=jobs.fottoWasSent(id);jobs.updateSettings(id,settings.toString());jobs.fottoDiscardUnsent(id);
   if(review){String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Sob Revisao",name.replaceFirst("(?i)\\.jpg$","_REVISAO.jpg"),id,"edited");jobs.set(id,"review","error",quality.reason);if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}return new SaveResult(true,wasSent);}
   if("done".equals(state)&&editedUri!=null&&!editedUri.isEmpty())jobs.overwrite(output,editedUri);else{String old=editedUri;jobs.clearEdited(id);Uri uri=jobs.save(output,"Editadas",name.replaceFirst("(?i)\\.jpg$","_Editada.jpg"),id,"edited");if(old!=null&&!old.isEmpty()&&!old.equals(uri.toString()))try{getContentResolver().delete(Uri.parse(old),null,null);}catch(Exception ignored){}}
   jobs.set(id,"done","error",null);if(!wasSent)FottoSync.kick(this);return new SaveResult(false,wasSent);
  }finally{original.delete();output.delete();}}
 void copyUri(String raw,File out)throws IOException{if(raw==null||raw.isEmpty())throw new IOException("Original não encontrado. O editor precisa do arquivo original preservado.");try(InputStream in=getContentResolver().openInputStream(Uri.parse(raw));OutputStream dst=new FileOutputStream(out)){if(in==null)throw new IOException("Original indisponível.");Jobs.copy(in,dst);}}
 void setControls(boolean enabled){for(SeekBar b:bars.values())b.setEnabled(enabled);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){destroyed=true;previewQueued=false;worker.shutdownNow();if(baseBitmap!=null)baseBitmap.recycle();if(previewBitmap!=null&&previewBitmap!=baseBitmap)previewBitmap.recycle();jobs.close();super.onDestroy();}
}
